= APIkit 3.9.3 Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

*May 31, 2018*

This release supports the Mule 3.9.3 Runtime release and corresponding Studio version.

There are no new features in this version. There are just a few enhancements and bug fixes.

== Compatibility

[%header%autowidth.spread]
|===
|Software |Version
|Mule Runtime |3.9.1 and later 3.9 versions
|===

== Big Fixes

Don't know how to parse org.mule.transport.NullPayload sending null payload.
When a Query Parameter type is defined as nil|string and a number is sent the response is 400 Bad Request.
Query Parameters are parsed as a ParameterMap and some other times as a HashMap.
Invalid APIKit WARN messages when two APIKit routers included in project.
The content-type request header is not case insensitive
Missing validation of RAML specified date time format
Multipart parameters are not being validated
API Specification not working on Raml parser (Merging not supported for nodes of type OverridableNativeTypeExpressionNode and TypeDeclarationNode)
Importing RAML from Design Center creates duplicate APIKit configurations


== See Also

* https://forums.mulesoft.com[MuleSoft Forum].
* https://support.mulesoft.com[Contact MuleSoft Support].
