= Anypoint Studio 7.3 with Mule Runtime 4.1.4 Update Site 2 Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

*February 4, 2019* +
*Build ID: 201902012052*

== Compatibility

[cols="30a,70a"]
|===
| Product | Version
| *Mule Runtime*
| Version: 4.1.4

|*Anypoint Studio*
|Version: 7.3.2 +
Build Id: 201902012052

|*Maven*
|Version: 3.3.9

|*DataWeave* +
|Version: 2.1.5

|*MUnit* +
|Version: 2.1.4 (munit-studio-plugin)

|*Eclipse* +
|Version: 4.7.2

|===

=== Runtime Compatibility

* Studio 7.3.2 comes bundled with Mule Runtime 4.1.4, however you can use it with earlier Mule Runtime versions as early as 4.1.1.

=== Studio Compatibility

* Projects created or updated with Studio 7.3.x or 7.2.x are not compatible with 7.1.x due to some improvements with the management of the mule-artifact.json file. The content of the file was reduced and part of the content used to be required by Studio 7.1.x. +
To fix this issue, you only need to update Studio to the latest 7.2.x version available. See xref:studio::update-workspace.adoc[Updating Workspaces] for more information.
* Workspaces created using Anypoint Studio 6.x or below are not compatible with Anypoint Studio 7 workspaces.

== What's New

The 7.3.2 Studio release includes a number of bug fixes.


== Hardware Requirements

* For most use cases, Anypoint Studio with the 4.1.4 Runtime does not change hardware or software requirements from the previous Studio 7  versions.
* MuleSoft recommends a minimum of 4GB of free RAM available on a developer workstation. As applications become complex, consider adding more RAM.

* 4GB of free memory available.
* 2GHz CPU.
* 10GB free hard drive space.

== Software Requirements

[cols="30a,70a"]
|===
| Software | Version
|Java Environments
| * Oracle JDK 1.8.0

This version of Studio is not compatible with Java 9 or Java 10. +
If you are having issues installing Studio, follow xref:7.2@studio::faq-jdk-requirement.adoc[this guide] to reconfigure your Java installation.

|Operating Systems |* MacOS 10.12.0 +
* Windows (32- and 64-bit) Windows 7, Windows 8, Windows 10 +
* RHEL 7.0 +
* Ubuntu 15.04 or later
|Suggested Web Browsers by Platform. +
_Studio will always use the OS default web browser_ | * Windows: +
** Microsoft Edge 25.0  +
** Internet Explorer 11 +
* Linux +
** Mozilla Firefox 51.0.1  +
* OS X +
** Safari 10.1
| Maven
| Studio comes with Maven 3.3.9 bundled, but you can externally use the versions: 3.3.3 or your own  3.3.9
|===

[NOTE]
--
If you are running McAfee VirusScan on your Windows OS, Eclipse-based Anypoint Studio may experience negative performance impacts. McAfee has suggested the following remedy https://kc.mcafee.com/corporate/index?page=content&id=KB58727[options].
--

== Known Issues

* Studio 7 only supports Mule 4.x projects. Due to the structure of projects, export format, xml and scripting language differences, we do not offer backwards compatibility with Mule 3.x runtimes.
* Some existing features in Studio 6.x are not yet supported in Studio 7: Custom Policies, API Sync, Anypoint Private Cloud.
* Anypoint Studio uses your configured default browser to display web content such as Exchange and the Runtime Manager UI when deploying an application to Anypoint Platform. If your default internet browser does not display this content correctly, you can configure Anypoint Studio to use a Mozilla/XULRunner runtime environment as the underlying renderer for the Web UI. +
Follow the xref:7.1@studio::faq-default-browser-config.adoc[FAQ: Troubleshooting Issues with Your Default OS Browser] for more details.
* Copybook import fails with no message.
* Copybook import file not copied to project.
* Mule modules needs to provide icons, today many of the modules have the generic icon.
* Running application "Pom.xml" is not updated when changing dependencies.
* Debugger: payload shown while debugging is partial but there is no way to view the rest of the payload
* Mule plugins with snapshot versions should always be regenerated.
* Datasense/Runtime not working correctly through proxy on connectors using TCP/IP or connectors which don’t yet support it.
* When importing a project with a runtime that is not installed in Studio there is no notification to the User.
* Define Metadata - selected schema file does not exist when I have an example JSON set for the metadata type.

== Bug Fixes

* Fixed error that caused non-valid keys being erased when calculating metadata fields.
* Fixed error of request config was being reported as incorrect when using placeholder for protocol.
* Fixed error where the *Configure mime type* did  not match with metadata.
* Fixed error that caused Maven dependencies not being filled in the project's libs classpathcontainer when importing a studio project using a project folder.
* Studio 7 now supports zoned decimal copybook format.
* Fixed "Invalid content was found starting with element" error when validating domain project in Studio 7.2.3.
* Fixed resolving metadata error When using Runtime 4.1.5 in 7.3.1 / 7.3.0.
* Fixed "Access Restriction" error for Spring Autowire.
* Fixed error when Time/size aggregator via Studio drag & drop mistakenly adds maxSize to sub-elements.
* Fixed `NullPointerException` while opening a mule file in non-mule project.
* It is now possible to reference an Object Store from a Caching Strategy through the UI.
* Fixed error for DataWeave UI not showing code when contains errors.
* Fixed issue causing parameters to be updated when db bulk-insert query is changed in Studio 7.3.x.
* Fixed issue causing `Config Ref` attribute to not be written in the XML when auto populated.
* Fixed issue causing a Transform Message defined in an Munit Test to create a source code in src/main/resources.
* Fixed issue causing Debugger to not stop at breakpoint in MUnit debug sessions.
* Fixed error prompted by 'Mule Application with Maven' option.
* Fixed issue causing the default values for "Frequency" and "Reconnection attempts" fields not being displayed when a Web Service Consumer is configured.
* Fixed error shown for projects with files with no extension.
* Added Idempotent Message Validator to the Studio palette.
* Fixed error displayed when configuring protocol of `<http:request-config />`.
* Namespace Directory from the XML Module now supports setting URN URI via the UI.
* Fixed issue causing Web Service Consume inside Until Successful to not resolve the output metadata.

== Support

* http://forums.mulesoft.com/[MuleSoft’s Forum].
* http://www.mulesoft.com/support-login[MuleSoft’s Customer Portal].
