= Anypoint Studio 7.3 with Mule Runtime 4.2.0 Update Site 4 Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

*May 9, 2019* +
*Build ID: 201905081644*

== Compatibility

[cols="30a,70a"]
|===
| Product | Version
| *Mule Runtime*
| Version: 4.2.0

|*Anypoint Studio*
|Version: 7.3.4 +
Build Id: 201905081644

|*Maven*
|Version: 3.3.9

|*DataWeave* +
|Version: 2.2.0

|*MUnit* +
|Version: 2.3.2 (munit-studio-plugin)

|*Eclipse* +
|Version: 4.7.2

|===

=== Runtime Compatibility

* Studio 7.3.4 is bundled with Mule Runtime 4.2.0, however, you can use it with earlier Mule Runtime versions such as as 4.1.4.

=== Studio Compatibility

* Projects created or updated with Studio 7.3.x or 7.2.x are not compatible with 7.1.x due to some improvements with the management of the `mule-artifact.json` file. The content of the file was reduced and part of the content used to be required by Studio 7.1.x. +
To fix this issue, you only need to update Studio to the latest 7.2.x version available. See xref:studio::update-workspace.adoc[Updating Workspaces] for more information.
* Workspaces created using Anypoint Studio 6.x or below are not compatible with Anypoint Studio 7 workspaces.

== What's New

* Studio 7.3.4 release includes two important bug fixes and comes bundled with Mule runtime enginge 4.2.0 runtime.

== Hardware Requirements

* For most use cases, Anypoint Studio with the 4.2.0 Runtime does not change hardware or software requirements from the previous Studio 7 versions.
* MuleSoft recommends a minimum of 4GB of free RAM available on a developer workstation. As applications become complex, consider adding more RAM.

* 4GB of free memory available.
* 2GHz CPU.
* 10GB free hard drive space.

== Software Requirements

[cols="30a,70a"]
|===
| Software | Version
|Java Environments
| * AdoptOpenJDK 8

This version of Studio is not compatible with Java 9 or Java 10. +
If you are having issues installing Studio, follow xref:7.2@studio::faq-jdk-requirement.adoc[this guide] to reconfigure your Java installation.

The only compatibility introduced for Java 11 is when using the Mule runtime engine version 4.2.0 and later. +
Studio still requires Java 8 to launch and run properly. You can install and configure Java 11 on your machine, but make sure to configure this JDK to be used by the embedded 4.2.x runtime running in Studio. +
See xref:studio::change-jdk-config-in-projects.adoc[Change the JDK from Studio] for instructions on how to do this.

|Operating Systems |* MacOS 10.12.0 +
* Windows (32- and 64-bit) Windows 7, Windows 8, Windows 10 +
* RHEL 7.0 +
* Ubuntu 15.04 or later
|Suggested Web Browsers by Platform. +
_Studio will always use the OS default web browser_ | * Windows: +
** Microsoft Edge 25.0  +
** Internet Explorer 11 +
* Linux +
** Mozilla Firefox 51.0.1  +
* OS X +
** Safari 10.1
| Maven
| Studio comes with Maven 3.3.9 bundled, but you can externally use the versions: 3.3.3 or your own  3.3.9
|===

[NOTE]
--
include::partial$studio/antivirus-impact.adoc[]
--

== Known Issues

* Studio 7 only supports Mule 4.x projects. Due to the structure of projects, export format, xml and scripting language differences, we do not offer backwards compatibility with Mule 3.x runtimes.
* Some existing features in Studio 6.x are not yet supported in Studio 7: Custom Policies, API Sync, Anypoint Private Cloud.
* Anypoint Studio uses your configured default browser to display web content such as Exchange and the Runtime Manager UI when deploying an application to Anypoint Platform. If your default internet browser does not display this content correctly, you can configure Anypoint Studio to use a Mozilla/XULRunner runtime environment as the underlying renderer for the Web UI. +
Follow the xref:7.1@studio::faq-default-browser-config.adoc[FAQ: Troubleshooting Issues with Your Default OS Browser] for more details.
* Copybook import fails with no message.
* Copybook import file not copied to project.
* Mule modules need to provide icons as today many of the modules have the generic icon.
* The `pom.xml` file of a running application is not updated when changing dependencies.
* Debugger: payload shown while debugging is partial but there is no way to view the rest of the payload
* Mule plugins with snapshot versions should always be regenerated.
* Datasense/Runtime not working correctly through proxy on connectors using TCP/IP or connectors which don’t yet support it.
* When importing a project with a runtime that is not installed in Studio there is no notification to the User.
* Define Metadata - selected schema file does not exist when an example JSON is set for the metadata type.

== Bug Fixes

* Fixed issue when Studio tried to upgrade workspaces that were using a packager version that didn't need to be upgraded.
* Fixed issue causing the editor to fail to open the SAP connector `Create IDoc` operation configuration.

== Support

* http://forums.mulesoft.com/[MuleSoft’s Forum].
* http://www.mulesoft.com/support-login[MuleSoft’s Customer Portal].
