= Amazon S3 Connector Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Support Category: Select

The Anypoint Amazon S3 Connector provides connectivity to the the Amazon S3 API, enabling you to interface with Amazon S3 to store objects, download and use data with other AWS services, and build applications that call for internet storage. Instant access to the Amazon S3 API enables seamless integrations between Amazon S3 and other databases, CMS applications such as Drupal, and CRM applications such as Salesforce.

Starting with v.4.0.0, the S3 Connector is licensed commercially with Anypoint Platform as with other Select connectors.  Prior versions remain freely available to the community.

== 5.3.2

June 3, 2019

=== Compatibility

The Amazon S3 connector is compatible with:

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime|4.1.0 and later
|AWS SDK for Java	|1.11.515
|===

=== Fixed in this Release

* Connector was unable to work with the lowercase region values or region values containing dashes. This issue is now fixed. [CONN-1942]

== 5.3.1

*May 8, 2019*

=== Compatibility

The Amazon S3 connector is compatible with:

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime|4.1.0 and later
|AWS SDK for Java	|1.11.515
|===

=== Fixed in this Release

* Connection to S3 no longer requires `s3:ListAllMyBuckets` permission. [SE-11434]

== 5.3.0

*April 9, 2019*

=== Compatibility

The Amazon S3 connector is compatible with:

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime|4.1.0 and later
|AWS SDK for Java	|1.11.515
|===

=== Features

* Added support for connecting to new AWS region endpoints.
* Connector now supports latest Amazon S3 storage classes: S3 Intelligent-Tiering, S3 Standard-IA, S3 One Zone-IA. (SE-11149)

== 5.2.1

*February 25, 2019*

=== Compatibility

The Amazon S3 connector is compatible with:

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime|4.1.0 and later
|AWS SDK for Java |1.11.79
|===

=== Fixed in this Release

* The connector was unable to properly stream large files to DataWeave. By adding the content length value as a message attribute, this issue was fixed.
* Test connection functionality did not work properly and is now fixed.

== 5.2.0

*August 16, 2018*

=== Compatibility

The Amazon S3 connector is compatible with:

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime|4.1.0 and later
|AWS SDK for Java	|1.11.79
|===

=== Features

* *Triggers* - You can now start a flow with the Amazon S3 Connector every time an object of a specific type is created, updated, or deleted.



== 5.1.1

*May 7, 2018*

=== Compatibility

The Amazon S3 connector is compatible with:

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |4.1.0 or later
|AWS SDK for Java	|1.11.79
|===

=== Fixed in this Release

The connector identified on the create object operation the content length of 0/null as the content having 0 as content length. It has now changed to have it as null.

== 5.1.0

*February 21, 2018*

=== Compatibility

The Amazon S3 connector is compatible with:

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |4.1.0 or later
|AWS SDK for Java	|1.11.79
|===

=== Fixed in this Release

AWS connectors shared a common library for the supported region endpoints that caused an issue when two different AWS connectors were used in a Mule app. This version fixes this issue.

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]

