= Amazon SQS Connector Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Support Category: Select

The Amazon SQS cloud connector provides an easy way to interface with the Amazon SQS API, allowing users to manage SQS queueing services without having to deal with the API directly.

Starting with v.4.0.0, the SQS Connector is licensed commercially with Anypoint Platform as with other Select connectors. Prior versions remain freely available to the community.

== 5.3.0

=== Compatibility

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime|4.1.0 and later
|AWS SDK for Java|1.11.515
|===

=== Features

* Added support for connecting to new AWS region endpoints.

== 5.2.1

*February 22, 2019*

=== Compatibility

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime|4.1.0 and later
|AWS SDK for Java|1.11.79
|===

=== Fixed in this Release

* In earlier versions, when Amazon SQS threw an error, SQS listener stopped working. Now the reconnect process for the listener is triggered in such case.

== 5.2.0

*August 28, 2018*

=== Compatibility

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime|4.1.0 and later
|AWS SDK for Java|1.11.79
|===

=== Fixed in this Release

* The issue where this connector threw java.lang.UnsupportedOperationException for sqs:delete-message-batch has been fixed.

== 5.1.1

*May 3, 2018*

=== Compatibility

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |4.1.0 and later
|AWS SDK for Java |1.11.79
|===

=== Fixed in this Release

Receive Message Source was failing to retrieve the Messages on the Queue rendering it useless. This version fixes this by making it work using an asynchronous client.

== 5.1.0

*February 21, 2018*

=== Compatibility

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |4.1.0 and later
|AWS SDK for Java |1.11.79
|===

=== Fixed in this Release

AWS connectors shared a common library for the supported region endpoints that caused an issue when two different AWS connectors were used in a Mule app. This version fixes this issue.

== 5.0.0

*November 18, 2017*

=== Compatibility

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |4.0.x and later
|AWS SDK for Java |1.11.79
|===

=== Features

* Migrated to Mule 4.

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
