= AS2 Connector Release Notes for Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Support Category: Premium

AS2 (Applicability Statement 2) is a specification about how to transport data securely and reliably over the internet. Security is achieved by using digital certificates and encryption.

The Mule Runtime supports the AS2 protocol through the AS2 Connector. The AS2 connector enables trading partners to transmit and receive AS2 messages with EDI-X12, EDIFACT, XML, or binary payloads.

== 4.0.7

*July 17, 2019*

=== Compatibility

[%header%autowidth.spread]
|===
|Software|Version
|Mule Runtime|4.1.0 and later
|Java| 8
|===

=== Fixed in this Release

* Corrected NullPointerException thrown during HTTP response generation for error conditions (SE-11935).


== 4.0.6

*June 11, 2019*

=== Compatibility

[%header%autowidth.spread]
|===
|Software|Version
|Mule Runtime|4.1.0 and later
|Java| 8
|===

=== Fixed in this Release

* The AS2 Connector did not refer an SSL certificate from the keyStorePath specified in the Secure Receiver Module ports.


== 4.0.5

*May 29, 2019*

=== Compatibility

[%header%autowidth.spread]
|===
|Software|Version
|Mule Runtime|4.1.0 and later
|Java| 8
|===

=== Fixed in this Release

* Certain receive requests failed because the App was trying to process deleted files.


== 4.0.4

*May 16, 2019*

=== Compatibility

[%header%autowidth.spread]
|===
|Software|Version
|Mule Runtime|4.1.0 and later
|Java| 8
|===

=== Fixed in this Release

* Some send and receive requests failed because the app was starting to process files before they were completely transferred.
* Releasing threads and file operations from the Send process increased the size of the thread pool and caused many operations to fail.
* The send and receive operations were not supported together in the same instance.

== 4.0.3

*April 26, 2019*

=== Compatibility

[%header%autowidth.spread]
|===
|Software|Version
|Mule Runtime|4.1.0 and later
|Java| 8
|===

=== Fixed in this Release

* The connector always sent the content signed with SHA256.

== 4.0.2

*March 28, 2019*

=== Compatibility

[%header%autowidth.spread]
|===
|Software|Version
|Mule Runtime|4.1.0 and later
|Java| 8
|===

=== Fixed in this Release

* The connector did not accept JKS and JCEKS keystores.
* The encryption and signing algorithm lists in the configuration are now tho separate ones. Previously, you were able to select a signing algorithm for encrypting and vice-versa, which would not work.
* The connector is now able to receive both signed and unsigned MDNs.

== 4.0.1

*February 20, 2019*

=== Compatibility

[%header%autowidth.spread]
|===
|Software|Version
|Mule Runtime|4.1.0 and later
|Java| 8
|===

=== Features

* Added Receiver Host configuration, which must be set to "0.0.0.0" for operating on CloudHub.

=== Fixed in this Release

* The connector would not accept incoming messages when run on CloudHub.
* Using signing throws ClassCastException.

== 4.0.0

*November 12, 2018*

=== Compatibility

[%header%autowidth.spread]
|===
|Software|Version
|Mule Runtime|4.1.0 and later
|Java|8
|===

=== Features

* Send - Allows you to send AS2 messages via HTTP or HTTPS.
* Receive - Enables a Mule application to receive messages following the AS2 protocol.

=== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
