= CAQH Connector Release Notes - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Support Category: Premium

The Anypoint Connector for CAQH lets you connect to the CAQH - ProView and DirectAssure Rosters using CAQH Data API. The connector exposes convenient methods to retrieve information about providers in real-time for credentialing and other purposes for Participating Organizations(PO).   

== V2.0

*May 4, 2019*

=== Compatibility

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime|Mule Enterprise Edition 4.0.0 and later
|Anypoint Studio|7.0 and later
|Java|8
|CAQH - ProView|v2
|CAQH - DirectAssure|v2
|===

=== Features

* *ProView Roster API Service* - Add/Update/Delete Roster Request.
* *Proview Roster Status Check* - To check status of providers in CAQH ProView.
* *DirectAssure Roster API Service* - Add/Update/Delete Roster Request.
* *DirectAssure Roster Status Check* - To check status of providers in CAQH DirectAssure.

=== Fixed in this Release
First version

== See Also

MuleSoft recommends that you install the latest version of Studio.

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
