= CAQH Connector Release Notes - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Support Category: Select

The Anypoint Connector for CAQH lets you connect to the CAQH - ProView and DirectAssure Rosters using CAQH Data API. The connector exposes convenient methods to retrieve information about providers in real-time for credentialing and other purposes for Participating Organizations. MuleSoft recommends that you install the latest version of Studio.

== 1.0.1

*May 21, 2019*

=== Compatibility

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime|Mule Enterprise Edition 4.0.0 and later
|Anypoint Studio|7.0 and later
|Java|8
|CAQH - ProView|v2
|CAQH - DirectAssure|v2
|===

=== Fixed in this Release

* Test connection bug is fixed for use in Design Center.
* The Get Provider Credentials operation's media type is changed to `application/xml`.
* Updated icon to CAQH.

== 1.0.0

*May 3, 2019*

=== Compatibility

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime|Mule Enterprise Edition 4.0.0 and later
|Anypoint Studio|7.0 and later
|Java|8
|CAQH - ProView|v2
|CAQH - DirectAssure|v2
|===

=== Features

* ProView Roster API Service: Add, update, or delete roster request for CAQH ProView.
* Proview Roster Status Check: Check status of providers in CAQH ProView.
* DirectAssure Roster API Service: Add, update, or delete roster Request for CAQH DirectAssure.
* DirectAssure Roster Status Check: Check status of providers in CAQH DirectAssure.

=== Fixed in this Release

First version.

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
