= FTP Connector Release Notes for Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== 1.2.3

*January 4, 2019*

=== Fixed Issues

* Fixed bug that made the connector get stuck while reading files from remote server, degrading performance. (MULE-16291)

== 1.2.2

*July 12, 2018*

=== Fixed Issues

* FtpFileAttributes throw NPE when FTPFile date is null. (MULE-15301)

== 1.2.1

*June 15, 2018*

=== Fixed Issues

* FTP:ILLEGAL_PATH is thrown during ftp write. (MULE-15104)
* FTP:Write deletes the directories and files when no filename is provided. (MULE-15172)

== 1.2.0

*April 24, 2018*

=== Fixed Issues

* FTP Connector should better inform on connection errors. (MULE-14993)

== 1.1.1

*February 2, 2018*

=== Fixed Issues

* ftp:listener has undescriptive display name. (MULE-14585)

== 1.1.0

*January 19, 2018*

=== New Features and Enhancements

This release includes the following enhancements, changes, and fixes:

* Added a message source that automatically polls for new files, while handling clustering, idempotency, post actions and watermark automatically.

