= WSC Connector Release Notes for Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== 1.3.3

*Jun 18, 2019*

=== Fixed Issues
* Fixed issue that caused performance degradation when using expression on configurations. (MULE-16970)


== 1.3.2

*May 3, 2019*

=== Fixed Issues
* Fixed issue that caused metadata not being collected when the location of the  WSDL was a relative path. (MULE-16876)
* Fixed issue that caused the signature and the timestamp to be incorrectly swapped when signing the timestamp. (MULE-16834)
* Fixed issue that caused the operation not being loaded on Studio.(MULE-16931)

== 1.3.1

*April 4, 2019*

=== Fixed Issues

* Fixed issue that caused the WDSL parsing to fail when an import with HTTPS was included in the WSDL. (MULE-16623)
* Fixed issue that caused the connector to fail finding attachments when an element has a namespace. (MULE-16592)
* Fixed issue that caused the connector to be unable to decrypt responses using the Key Transport Algorithm RSA 1.5. (MULE-16605)
* Fixed issue that caused the connector to be unable to generate the signature value, CXF library version upgraded. (MULE-16637)

== 1.3.0

*February 11, 2019*

=== New Features and Enhancements

* Able to configure encryption algorithms. (MULE-16099, MULE-16099)
* Able to configure signature algorithm. (MULE-16100, MULE-11299)
* Able to configure which parts of the request should be signed or encrypted. (MULE-16094)
* New web service consumer connector icon. (MULE-16376)

=== Fixed Issues

* Expose HTTP status code. (MULE-16333)
* Fixed issue that caused NPE when a SOAP attachment didn't include a MIME type. (MULE-16441)
* Fixed issue that cause the execution of MUnit test to hang if a HTTP:CONNECTIVITY error is thrown. (MULE-16221)

== 1.2.4

*January 29, 2019*

=== Fixed Issues

* Update net.sf.Saxon to 9.9.1-1. (MULE-16393)

== 1.2.3

*January 25, 2019*

=== Fixed Issues

* Fixed issue that caused XML Schema choice Element not being handled. (MULE-16235)

== 1.2.2

*December 20, 2018*

=== Fixed Issues

* Fixed issue when parsing a WSDL that imports another WSDL.  (MULE-16231)
* Fixed issue that caused NPE when configuring invalid headers to the consume operation. (MULE-16177)

== 1.2.1

*Nov 12, 2018*

=== Fixed Issues

* Fixed issue when resolving metadata of a WSDL that contains multiple operations with the same name for different ports.  (MULE-15988)
* Fixed issue when parsing embedded Base64 attachments. (MULE-15790)

== 1.2.0

*October 29, 2018*

=== New Features and Enhancements

This release includes major performance improvements to resolving values for configurations
and DataSense.

=== Known Limitations and Workarounds

* RPC WSDLs are not supported.

=== Fixed Issues

* WSC headers metadata is being badly generated. (MULE-15922)
* Improve the WSC value provider performance. (MULE-15885)
* WSC should allow timeout configuration for default HTTP config. (MULE-15844)
* Make WSC take advantage of the metadata cache. (MULE-15551)
* Upgrade `commons-lang3` to 3.7. (MULE-15082)
* Upgrade Guava to 25.1. (MULE-15079)
* WSC cannot load WSDL files inside JAR files. (MULE-14996)

== 1.1.1

*March 26, 2018*

=== Known Limitations and Workarounds

* RPC WSDLs are not supported

=== Fixed Issues

* WSC is affected by CVE-2017-9735. (EE-5773)

== 1.1.0

*January 19, 2018*

=== New Features and Enhancements

This release includes the following enhancements, changes, and fixes:

* Support for multipart messages
* Added configuration hints through Value Providers
* Same experience for MTON and Soap with Attachments
* Improved UX

=== Known Limitations and Workarounds

* RPC WSDLs are not supported

=== Upgrade Requirements

Mule 4.1

=== Fixed Issues

* WSC Connector exports internal classes. (MULE-14445)
* Upgrade to CXF 3.2.1. (MULE-14060)
* Correct event is not used when running with custom HTTP transport config. (MULE-14388)

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
