= FTP Connector Release Notes for Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== 1.3.0

*May 23, 2019*

=== Minimum Mule Version

*4.1.1*

=== New Features and Enhancements

* The `timeBetweenSizeCheck` setting prevents the connector from processing files while they are being written.

=== Fixed Issues

* FTP connector should not log the full stack trace in warn level when failing to log out a connection. (MULE-16825)
* Fixed a regression that affected the use of `ftp:listener` without specifying a directory. (MULE-16818)

== 1.2.6

*April 22, 2019*

=== Minimum Mule Version

*4.1.1*

=== Fixed Issues

* Fixed an issue that prevented reading a file that had a space in its name. (MULE-16729)
* Fixed an issue that prevented virtual directories to be listed or use the polling source in them. (MULE-16625)

== 1.2.5

*March 25, 2019*

=== Minimum Mule Version

*4.1.1*

=== Fixed Issues

* Improved the FTP Write operation's performance when writing on remote servers. (MULE-16557)
* Fixed a bug that prevented the usage of the list operation on some FTP server configurations. (MULE-16591)

== 1.2.4

*January 21, 2019*

=== Minimum Mule Version

*4.1.1*

=== Fixed Issues

* Fixed bug that made the List operation take too long when the listed directory contained a large number of files. (MULE-16346)

== 1.2.3

*January 4, 2019*

=== Minimum Mule Version

*4.1.1*

=== Fixed Issues

* Fixed bug that made the connector get stuck while reading files from a remote server, degrading performance. (MULE-16291)

== 1.2.2

*July 12, 2018*

=== Minimum Mule Version

*4.1.0*

=== Fixed Issues

* `FtpFileAttributes` threw NPE when FTPFile date was null. (MULE-15301)

== 1.2.1

*June 15, 2018*

=== Minimum Mule Version

*4.1.0*

=== Fixed Issues

* FTP:ILLEGAL_PATH is thrown during FTP write. (MULE-15104)
* FTP:Write deletes the directories and files when no filename is provided. (MULE-15172)

== 1.2.0

*April 24, 2018*

=== Minimum Mule Version

*4.1.0*

=== Fixed Issues

* FTP connector should better inform on connection errors. (MULE-14993)

== 1.1.1

*February 2, 2018*

=== Minimum Mule Version

*4.1.0*

=== Fixed Issues

* ftp:listener has undescriptive display name. (MULE-14585)

== 1.1.0

*January 19, 2018*

=== Minimum Mule Version

*4.1.0*

=== New Features and Enhancements

* Added a message source that automatically polls for new files, while handling clustering, idempotency, post actions, and watermark automatically.

== See Also

* https://www.mulesoft.com/exchange/org.mule.connectors/mule-ftp-connector/[Anypoint Exchange FTP Connector]
* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
