= File Connector Release Notes for Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Support Category: Select

== 1.3.0

*Jul 15, 2019*

=== Minimum Mule Version

*Mule 4.1.1*

=== New Features and Enhancements

* Parameters "updatedInTheLast" and "notUpdatedInTheLast" were added to the file matcher along with the "timeUnit" parameter. These enables the developer to make a list operation or listener filter files that may still being written, or are too old.

=== Fixed Issues

* Add "(Not) Updated in the last..." capability to File Matcher. (MULE-17103)

== 1.2.4

*May 10, 2019*

=== Minimum Mule Version

*Mule 4.1.1*

=== Fixed Issues

* The List operation fails to list files in a directory when encountering a file without read permissions. (MULE-16819)
* In Windows, the List operation fails to list files in a directory where a file has been deleted just before the list operation is executed. (MULE-16827)
* NoSuchFileExceptions with file listeners in clustered environment. (MULE-16766)
* File Listener with watermark skips a file. (MULE-15792)

== 1.2.3

*April 29, 2019*

=== Minimum Mule Version

*Mule 4.1.1*

=== Fixed Issues

* The List operation failed when listing a directory that contained a file that had been moved or deleted. (MULE-16766)
* The listener stopped polling when failing to list a file. Now the connector either lists all files, or fails entirely. (MULE-15792)

== 1.2.2

*April 3, 2019*

=== Minimum Mule Version

*Mule 4.1.1*

=== Fixed Issues

* File Connector should not gather attributes twice on the list operation. (MULE-16356)
* File Connector doesn't fail when a file lock is not obtained. (MULE-16353)
* Removed Guava dependency. (MULE-14275)
* Upgraded File Commons dependency to 1.2.1.
* Upgraded Commons IO to 2.6.

== 1.2.1

*November 8, 2018*

=== Minimum Mule Version

*Mule 4.1.1*

=== Fixed Issues

* File Directory listener leaks open files. (MULE-15687)
* Directory parameter should have path support. (MULE-14128)

== 1.2.0

*August 14, 2018*

=== Minimum Mule Version

*Mule 4.1.0*

=== New Features and Enhancements

* You can make use of `timeBetweenSizeCheck` to prevent the connector from processing files while they are being written.

=== Fixed Issues

* File getting partial files. (MULE-14881)
* `file:listener` does not delete source file when moving to a file that already exists. (MULE-15030)
* File Polling Source does not communicate their Attributes correctly. (MULE-15351)
* When File connector listeners are configured to move to a directory, auto-delete deletes files but does not move them. (MULE-15448)
* Encoding parameter should be removed from the write operation. (MULE-15503)

== 1.1.3

*May 7, 2018*

=== Minimum Mule Version

*Mule 4.1.0*

=== New Features and Enhancements

* Fixed an issue that happened when using a filter by filenamePattern, failing to search files recursively in folders.

=== Fixed Issues

* File Connector does not check for files recursively if a filenamePattern is given. (MULE-14863)

== 1.1.2

*March 14, 2018*

=== Minimum Mule Version

*Mule 4.1.0*

=== Fixed Issues

* Connectors doesn't communicate correctly if their POJOs properties are nulleable or not. (MULE-14701)

== 1.1.1

*February 2, 2018*

=== Fixed Issues

* file:listener has undescriptive display name. (MULE-14584)

== 1.1.0

*January 19, 2018*

=== New Features and Enhancements

This release includes the following enhancements, changes, and fixes:

* Added a message source that automatically polls for new files, while handling clustering, idempotency, post actions and watermark automatically.

=== Upgrade Requirements

Mule 4.1

=== Fixed Issues

* Support processing files in all nodes of the cluster as we did in 3.x. (MULE-14128)

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
