= IBM MQ Connector Release Notes for Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Support Category: Select

== 1.2.3

*March 29, 2019*

=== New Features and Enhancements

* Fixed reconnection issue when Queue Manager is shutdown while handling REPLY_TO.
* Fixed IBM MQ Client unhandled exception when cleaning a consumer's message listener.
* Cleanup of IBM MQ exception listener state, when a cached connection is not cleaned up.

== 1.2.0

*February 5, 2019*

=== New Features and Enhancements

* Out of the box support for TLS/SSL configurations.

== 1.1.2

*January 14, 2019*

=== New Features and Enhancements

* Fixed connection leaks. These leaks could happen when a Publish action failed internally
or when doing an automatic ReplyTo when using the "On New Message" source.

== 1.1.1

*November 7, 2018*

=== New Features and Enhancements

* Fixed issue that prevented the connector from setting a Client ID, required for
durable subscriptions.

=== Fixed Issues

* Unable to set the Client ID on an IBM MQ Connection

== 1.1.0

*October 26, 2018*

=== New Features and Enhancements

* Fixed issue that prevented correct execution when using XA Transactions.
* Message Listener can be configured to propagate the correlation ID when doing a reply.

=== Fixed Issues

* XA Transaction is not working for IBM MQ Connector

== 1.0.0

*June 29, 2018*

=== Features and Enhancements

* Release of IBM MQ Connector, which supports consuming and publishing messages through the JMS API.
* https://docs.mulesoft.com/connectors/ibm/ibm-mq-connector[IBM MQ Documentation]

=== Mule Version

Mule 4.1.1

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
