= EDIFACT Connectors Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Support Category: Premium

The EDIFACT EDI connector lets you convert EDIFACT messages to and from DataWeave-compatible representations using lists and maps.

== 1.3.4

*April 2019*

=== Fixed in this Release

* Fixed the infinite loop when missing a UNT segment. (SE-10442)
* Added a specific error message when missing a UNT segment. (SE-10442)
* Added support for integer value types for implied decimal format. (SE-11494)
* Corrected escape character handling on read. (SE-9795)
* Eliminated NPE when space value is set for a delimiter character. (SE-11312)
* Changed the shaded package name for debugger compatibility. (SE-10796)

=== Compatibility


[%header,cols="30a,70a"]
|===
|Application or Service |Version
|Mule Runtime |Mule 3.6.0 and later
|EDIFACT |d93a, d95b, d96a, d97a, d98b, d99a, d99b, d00a, d01b, d02a, and d03a
|===

== 1.3.1

*January 19, 2018*

=== Compatibility

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime|Mule 3.6.0 and later
|===

== 1.3.0

*November 7, 2017*

===  Compatibility

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime|Mule 3.6.0 and later
|===

=== Fixed Issues

* Changed parser to interpret UNOY syntax identifier as UTF-8 encoding by default, for consistency with writer code.

=== New Features

* Added receiveEncodingOverride configuration parameter to allow the user to specify the receive character encoding
* Added support for UNOW syntax identifier in parser, interpreting this as UTF-8 encoding.

== 1.2.2

*December 27, 2016*

=== Compatibility

[%header,cols="50,50"]
|===
|Application/Service|Version
|Mule Runtime|Mule 3.6.0 and newer
|===

=== Fixed Issues

* Supports '\n' as a segmentTerminator.

== 1.2.1

*September 28, 2016*

=== Compatibility

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime|Mule 3.6.0 and later
|===

===  New Features

* Added support for inline components in ESL schema definitions.
* Added support for writing DataWeave-compatible types.
* Improved overlay handling, allowing segments to specify only modified components and change component type
* Support writing repeating composite.

=== Fixed Issues

* Corrected some off-by-one errors in reporting data errors, and some segment off-by-one errors.
* Changed group keys in data, eliminating position numbers previously used at start of key.
* Correct check for data present when reading a composite to work correctly when first value of composite is empty.
* Abort parsing of message if the initial UNA/UNB cannot be read (since there's no way to know the delimiters being used for message).

== 1.0.2

*March 9, 2016*

=== Compatibility

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime|Mule 3.6.0 and later
|===

=== New Features

* Add more details to error logging.

== 1.0.1

*November 10, 2015*

=== Compatibility

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime|Mule 3.6.0 and later
|===

=== New in This Release

This release contains the following fixes:

* Fixed dead lock when acquiring lock to increment control number
* Writing now correctly fails when writing invalid characters and repeating values outside defined limits
* New icons for the connector

For more information, such as how to install or use these modules, see
xref:partner-manager::index.adoc[Anypoint B2B], xref:partner-manager::edifact-module.adoc[EDIFACT Module], and xref:partner-manager::x12-module.adoc[X12 Module].

=== Migration Guide

No application changes are needed from 1.0.0.


== 1.0.0

*Sept 21, 2015*

=== Compatibility

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime|Mule 3.6.0 and later
|===


=== New in This Release

This release contains many improvements, including:

* Support for reading/writing multiple versions of the same transaction type within a single message
* Additional EDIFACT message types d03A and d95B
* Improved structure usability with DataWeave and MEL by including "Loop" in the key name for groups and using underscores instead of spaces. You will need to update your integrations appropriately for this (see below).
* Improved validation logic on writing.
* Many bug fixes

For more information, such as how to install or use these modules, see
xref:partner-manager::index.adoc[Anypoint B2B], xref:partner-manager::edifact-module.adoc[EDIFACT Module], and xref:partner-manager::x12-module.adoc[X12 Module].

=== Migration Guide

All of your transformations and expressions that references parts of the EDI message structure must be updated for the following changes:

* The "Transactions" list has been changed to "TransactionSets" and now has an additional level for the version of the transactions.
** Example: payload.Transactions."850" now becomes payload.TransactionSets.v5010."850"
* All keys no longer have spaces - instead they have underscores
** Example: payload."0100 PO1" becomes payload."0100_PO1"
* Any segment that is a loop
** Example: payload.Detail."0100 PO1" becomes payload.Detail."0100_PO1_Loop"

== Known Issues

The following issues apply to all versions:

* EDIFACT packages (containers for binary data) are not supported, and cause errors if you attempt to use them.
* EDIFACT interactive exchanges (using UIB header segment and UIZ trailer segment) are not supported.
* Code values are not currently verified for either reading or writing.
* EDIFACT groups are not supported.

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
