= HL7 MLLP Connector Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

*November 2018*

_Premium_

The Mule HL7 MLLP connector provides connectivity and parsing functionality for MLLP messages.

xref:connectors::hl7/hl7-mllp-connector.adoc[HL7 MLLP Connector Guide]

== 2.0.4 

*January 11, 2019*

=== Compatibility

[%header%autowidth.spread]
|===
|Software |Version
|Mule Runtime |4.0.0 and later
|===

=== Features

* The start-of-block character is now configurable.

=== Fixed in this Release

* The end-of-block character was incorrectly marked as required. It is now optional.
* Under certain scenarios, all messages received after the first one would fail, with the error message `Message does not start with 'MSH'`. This was fixed.

== 2.0.3 

*November 16, 2018*

This update fixes an response issue, and adds the new *sendAndReceive* operation.

=== Compatibility

[%header%autowidth.spread]
|===
|Software |Version
|Mule Runtime |4.0.0 and later
|===

=== Fixed in this Release

* Mule 4 HL7 MLLP Connector does not wait for a response after sending a message out. Added new operation sendAndReceive.

== 2.0.2

*October 1, 2018*

=== Compatibility

[%header%autowidth.spread]
|===
|Software |Version
|Mule Runtime |4.0.0 and later
|===

=== Fixed in this Release

Depending on the way messages were sent to the connector, it would stop receiving requests after the first one. This was fixed.

== 2.0.1

*September 20, 2018*

=== Compatibility

[%header%autowidth.spread]
|===
|Software |Version
|Mule Runtime |4.0.0 and later
|===

=== Fixed in this Release

ACK like messages weren't flowing back to sender.

== 2.0.0

*June 18, 2018*

=== Compatibility

[%header%autowidth.spread]
|===
|Software |Version
|Mule Runtime |4.0.0 and later
|Anypoint Studio |7.1 and later
|===

=== Features

* Receive Message - The HL7 MLLP connector provides the functionality to receive MLLP messages.
* Send Message - The HL7 MLLP connector provides the functionality to send MLLP messages.

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
