= LDAP Connector Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: release notes, ldap, active directory, connector

_Select_

*October 2018*

The Lightweight Directory Access Protocol (LDAP) is an open, vendor-neutral, industry standard application protocol for accessing and maintaining distributed directory information services over an Internet Protocol (IP) network. The LDAP connector allows Mule applications to interact with LDAP servers.

== 3.1.1

*October 26, 2018*

=== Compatibility

The LDAP Connector is compatible with:

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime|4.0.0 and later
|Java|1.8 or higher
|===

=== Fixed in this Release

* The connector failed when the `authentication` parameter was not set. This was fixed and now it works as expected.

== 3.1.0

*September 13, 2017*

=== Compatibility

The LDAP Connector is compatible with:

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime|4.0.0 and later
|Java|1.8 or higher
|===

=== Features

* The connector now has 2 triggers one for new objects and one for modified objects. Using these 2 triggers one can receive notifications if ldap entries are created or updated since the app was started or since a configured timestamp that can be specified when configuring the trigger.

== 3.0.0

*November 18, 2017*

Release notes for version 3.0.0 of the LDAP connector.

=== Compatibility

The LDAP Connector is compatible with:

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime|4.0.0 and later
|Java|1.8 and later
|===

=== Features

* The LDAP connector is built with the new AnyPoint SDK (aka Extensions Framework) v1.0.0-rc-SNAPSHOT.

=== Fixed in this Release

* Fixed an exception when member ranges were used along schemaEnabled.
  (P.S. : Member ranges are feature specific to Active Directory.)
* Added support for custom trust store through Extended configuration parameters.

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com[Contact MuleSoft Support]
