= Microsoft SharePoint Online Connector Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: release notes, connectors, sharepoint, online

_Select_

*Guide*: xref:3.9@mule-runtime::microsoft-sharepoint-online-connector.adoc[Microsoft SharePoint Online Connector]

== Version 1.0.1 - April 4, 2019

=== Features

None.

=== Fixed in this release

- When using native query language for reference fields, Object To JSON throws an exception: `java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to java.lang.Integer`; fixed the issue by improving the fields lookup algorithm. (SE-9230)

*Guide*: xref:3.9@mule-runtime::microsoft-sharepoint-online-connector.adoc[Microsoft SharePoint Online Connector]

== 1.0.0

New release of the SharePoint Online version.

Supported operations:

* Lists and List Items API: Create, delete, retrieve, update lists, and list items.
* Files and Folders API:
** Files: Add, retrieve content, retrieve metadata, delete, check out, undo check out, check in, publish, unpublish, approve, deny, recycle, and copy files.
** Folders: Create, delete, and retrieve folders.

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com[Contact MuleSoft Support]
