= MongoDB Connector Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Support Category: Select

Mule supports MongoDB integration by using the MongoDB Java Driver.

== 5.3.1

*April 08, 2019*

=== Compatibility

[%header%autowidth.spread]

|===

|Software|Version

|Mule Runtime|4.0.0 and later

|MongoDB|3.8

|===

=== Fixed in this version

* Mongo get-file-content operation  is expecting user to pass internal type of connector. (SE-10073)
* MongoDB triggers fails with java.lang.NullPointerException. (SE-11354)
* Domain name does not have a recognized public suffix Mongo Connector. (SE-10149)

== 5.3.0

*September 26, 2018*

=== Compatibility

[%header%autowidth.spread]
|===
|Software|Version
|Mule Runtime|4.0.0 and later
|MongoDB|3.8
|===

=== New Features

* Added Triggers for *new*, *modified*, and *deleted* Objects.
These triggers allow you to execute a flow each time a new Object is created, or when an existing Object is modified or deleted.

== 5.2.0

*September 4, 2018*

=== Compatibility

[%header%autowidth.spread]
|===
|Software|Version
|Mule Runtime|4.0.0 and later
|MongoDB|3.8
|===

=== New Features

* Added the new operation 'Execute Generic Command' to run any MongoDB command using the connector.
This command is supplied as a parameter in the form of a MongoDB document.
* MongoDB Java Driver Update - The connector has been updated with the MongoDB Java Driver v3.8.0.

== 5.1.1

*June 28, 2018*

=== Compatibility

[%header%autowidth.spread]
|===
|Software|Version
|Mule Runtime|4.0.0 and later
|MongoDB|3.6
|===

=== Fixed in This Version

* Connector did not work using the 3.6 driver when a TLS global context was not present. This error appeared:

[source,text,linenums]
----
2018-06-28T18:07:06.764+0000 I NETWORK  [conn262] Error receiving request from client: 
SSLHandshakeFailed: SSLHandshakeFailed. Ending connection from ...
----

Now it is working.

== 5.1.0

*June 28, 2018*

=== Compatibility

[%header%autowidth.spread]
|===
|Software|Version
|Mule Runtime|4.0.0 and later
|MongoDB|3.6
|===

=== New Features

* MongoDB Java Driver Update - The connector has been updated with the MongoDB Java Driver v3.6.0.

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
