= Microsoft Service Bus Connector Release Notes for Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Support Category: Select

== 2.0.3 

*February 22, 2019*

=== Compatibility

[%header%autowidth.spread]
|===
|Software | Version
|Mule Runtime | 4.0.0 and later
|Microsoft Azure Service Bus (Cloud) | -
|Microsoft Windows Service Bus (on-premises) | -
|===

=== Fixed in this Release

* Connection leaks were fixed.
* The connector would stop receiving messages when the flow threw an error. This was fixed.

=== Known Issues

* Automatic completion of queue and topic names, subscriptions, and rules may not work in Design Center.

== 2.0.2 

*December 5, 2018*

=== Compatibility

[%header%autowidth.spread]
|===
|Software | Version
|Mule Runtime | 4.0.0 and later
|Microsoft Azure Service Bus (Cloud) | -
|Microsoft Windows Service Bus (on-premises) | -
|===

=== Fixed in this Release

* Previously, the connector leaked connections while publishing a message to a topic using the default caching strategy. The connector uses one or two JMS connections based on the configuration.

=== Known Issues

* Automatic completion of queue or topic names, subscriptions, and rules may not work in Design Center.
* In Design Center, the Live View feature does not work for most operations. In addition to this, the application log may be flooded with several "Could not serialize object" errors.

== 2.0.1

*October 23, 2018*

=== Compatibility

[%header%autowidth.spread]
|===
|Software | Version
|Mule Runtime | 4.0.0 and later
|Microsoft Azure Service Bus (Cloud) | -
|Microsoft Windows Service Bus (on-premises) | -
|===

=== Features

None.

=== Fixed in this Release

* *Manual ACK not working* - Previously, when attempting to do a manual acknowledge of a message, the connector would lock the flow. This was now fixed, and doing this works as expected.

=== Known Issues

* Automatic completion of queue and topic names, subscriptions and rules may not work in Design Center.
* In Design Center, the Live View feature will not work for most operations. In addition to this, the application log may be flooded with several "Could not serialize object" errors.
* The connector leaks connections while publishing a message to a topic using the default caching strategy. As a workaround, configure the connector to disable the caching strategy.

== 2.0.0

*May 28, 2018*

=== Compatibility

[%header%autowidth.spread]
|===
|Software | Version
|Mule Runtime | 4.0.0 and later
|Microsoft Azure Service Bus (Cloud) | -
|Microsoft Windows Service Bus (on-premises) | -
|===

=== Features

* Added support for Mule 4.

=== Known Issues

* Automatic completion of queue and topic names, subscriptions, and rules may not work in Design Center.
* In Design Center, the Live View feature does not work for most operations. In addition to this, the application log may be flooded with several "Could not serialize object" errors.
* The connector leaks connections while publishing a message to a topic using the default caching strategy. As a workaround, configure the connector to disable the caching strategy.

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
