= NetSuite Connector Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Support Category: Select

The Anypoint Connector for NetSuite synchronizes data and automates business processes between NetSuite and third-party applications, either on-premises or in the cloud.

== 8.3.0

*March 29, 2019*

=== Compatibility

[%header%autowidth.spread]
|===
|Software | Version
|Mule Runtime | 4.0.0 and later
|SuiteTalk API | 2017.2
|===

[NOTE]
The NetSuite version is _not_ the same as the SuiteTalk API version. Your account may run on a version of NetSuite different than the version of the the API you are using.

=== Features

* Token authentication is now supported for RESTlet operations. (SE-11335)

=== Fixed in this Release

* Some metadata resolving routines were optimized.

== 8.2.1

*January 15, 2019*

=== Compatibility

[%header%autowidth.spread]
|===
|Software | Version
|Mule Runtime | 4.0.0 and later
|SuiteTalk API | 2017.2
|===

[NOTE]
The NetSuite version is _not_ the same as the SuiteTalk API version. Your account may run on a version of NetSuite different than the version of the the API you are using.

=== Features

* Headers Preferences - Added a new parameter in the configuration to explicitly disable sending the `runServerSuiteScript` tag in Preferences header.

=== Fixed in this Release

* Name is null error - When performing an upsert record with a null Name, a NullPointerException would occur. Fixed by properly handling null names.

== 8.2.0

*August 4, 2018*

=== Compatibility

[%header%autowidth.spread]
|===
|Software | Version
|Mule Runtime | 4.0.0 and later
|SuiteTalk API | 2017.2
|===

[NOTE]
The NetSuite version is _not_ the same as the SuiteTalk API version. Your account may run on a version of NetSuite different than the version of the the API you are using.

=== Features

* *Triggers* - You can now start a flow with the NetSuite Connector every time an object of a specific type is created, updated, or deleted.

=== Fixed in this Release

None.

=== Known Issues

None.

== 8.1.1

*July 13, 2018*

=== Compatibility

[%header%autowidth.spread]
|===
|Software | Version
|Mule Runtime | 4.0.0 and later
|SuiteTalk API | 2017.2
|===

[NOTE]
The NetSuite version is _not_ the same as the SuiteTalk API version. Your account may run on a version of NetSuite different than the version of the the API you are using.The NetSuite version is _not_ the same as the SuiteTalk API version. Your account may run on a version of NetSuite different than the version of the the API you are using.

=== Fixed in this Release

* Search operation returned an empty response in Mac and a parsing error in Windows.

=== Known Issues

None.

== 8.1.0

*March 13, 2018*

=== Compatibility

[%header%autowidth.spread]
|===
|Software | Version
|Mule Runtime | 4.0.0 and later
|SuiteTalk API | 2017.2
|===

[NOTE]
The NetSuite version is _not_ the same as the SuiteTalk API version. Your account may run on a version of NetSuite different than the version of the the API you are using.

=== Features

* Support for SuiteTalk API version 2017.2. For a detailed list of changes, log into NetSuite, open Help Center and navigate to New Release > Release Notes > NetSuite 2017.2 Release Notes > SuiteTalk (Web Services) Integration.

== 8.0.0

*November 18, 2017*

=== Compatibility

[%header%autowidth.spread]
|===
|Software | Version
|Mule Runtime | 4.0.0 and later
|SuiteTalk API | 2017.1
|===

The NetSuite version is _not_ the same as the SuiteTalk API version. Your account may run on a version of NetSuite different than the version of the the API you are using.

=== Features

* Support for SuiteTalk API version 2017.1. GA For a detailed list of changes, log into NetSuite, open Help Center and navigate to New Release > Release Notes > NetSuite 2017.1 Release Notes > SuiteTalk (Web Services) Integration.
* Added support for Mule 4.

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
