= NetSuite Connector Release Notes - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Support Category: Select

The Anypoint Connector for NetSuite synchronizes data and automates business processes between NetSuite and third-party applications, either on-premises or in the cloud.

== 9.0.1

*July 3, 2019*

=== Compatibility

[%header%autowidth.spread]
|===
|Software | Version
|Mule Runtime | 4.0.0 and later
|SuiteTalk API | 2018.2
|===

[NOTE]
The *NetSuite* version is *not* the same as the *SuiteTalk API* version. Your account may be running on a version of NetSuite different than the version of the API you are using.

=== Fixed in this Release

* Fixed potential XXE vulnerability. (CONN-2112)

=== Known Issues

None.


== 9.0.0

*June 7, 2019*

=== Compatibility

[%header%autowidth.spread]
|===
|Software | Version
|Mule Runtime | 4.0.0 and later
|SuiteTalk API | 2018.2
|===

[NOTE]
The *NetSuite* version is *not* the same as the *SuiteTalk API* version. Your account may be running on a version of NetSuite different than the version of the API you are using.

=== Features

* Support for SuiteTalk API version 2018.2. For a detailed list of changes, log into NetSuite, open Help Center and navigate to New Release > Release Notes > NetSuite 2018.2 Release Notes > SuiteTalk (Web Services) Integration.
* The list operations (Add list, Delete list, Update list and Upsert list) now return information about the status of the result in each record.

=== Fixed in this Release

None.

=== Known Issues

None.

=== Migrating from Older Versions

* In the old versions, the list operations returned a list of type `BaseRef`. Now they return a list of type `WriteResponse`. The `WriteResponse` has as fields: the `baseRef` (like the previous versions) and also the `status`. The `status` field is a structure that contains the information about whether the operation was successful (`isSuccess` Boolean) and details of the status (`statusDetail` structure). In case of error the structure of `statusDetail` indicates in the field `type` if it was an ERROR, in the field `code` indicates the type of error (for example: 'INVALID_KEY_OR_REF') and finally in the field `message` contains details of the error (as the value and/or field involved).

== 8.3.4

*June 26, 2019*

=== Compatibility

[%header%autowidth.spread]
|===
|Software | Version
|Mule Runtime | 4.0.0 and later
|SuiteTalk API | 2017.2
|===

[NOTE]
The NetSuite version is not the same as the SuiteTalk API version. Your account may run on a different NetSuite version than the version of the the API you are using.

=== Features

None.

=== Fixed in this Release

* Fixed potential XXE Vulnerability. (CONN-2112)

== 8.3.3

*June 11, 2019*

=== Compatibility

[%header%autowidth.spread]
|===
|Software | Version
|Mule Runtime | 4.0.0 and later
|SuiteTalk API | 2017.2
|===

[NOTE]
The NetSuite version is not the same as the SuiteTalk API version. Your account may run on a different NetSuite version than the version of the the API you are using.

=== Features

None.

=== Fixed in this Release

* HTTP Proxy for RESTlet operations: a new fix was implemented. Previously, the proxy configuration was ignored by the dynamic endpoint resolution. It now works as expected. (SE-11716)

== 8.3.2

*May 22, 2019*

=== Compatibility

[%header%autowidth.spread]
|===
|Software | Version
|Mule Runtime | 4.0.0 and later
|SuiteTalk API | 2017.2
|===

[NOTE]
The NetSuite version is not the same as the SuiteTalk API version. Your account may run on a different NetSuite version than the version of the the API you are using.

=== Features

None.

=== Fixed in this Release

* The HTTP Proxy for RESTlet operations now works in all scenarios. (SE-11716)

== 8.3.0

*March 29, 2019*

=== Compatibility

[%header%autowidth.spread]
|===
|Software | Version
|Mule Runtime | 4.0.0 and later
|SuiteTalk API | 2017.2
|===

[NOTE]
The NetSuite version is _not_ the same as the SuiteTalk API version. Your account may run on a version of NetSuite different than the version of the the API you are using.

=== Features

* Token authentication is now supported for RESTlet operations. (SE-11335)

=== Fixed in this Release

* Some metadata resolving routines were optimized.

== 8.2.1

*January 15, 2019*

=== Compatibility

[%header%autowidth.spread]
|===
|Software | Version
|Mule Runtime | 4.0.0 and later
|SuiteTalk API | 2017.2
|===

[NOTE]
The NetSuite version is _not_ the same as the SuiteTalk API version. Your account may run on a version of NetSuite different than the version of the the API you are using.

=== Features

* Headers Preferences - Added a new parameter in the configuration to explicitly disable sending the `runServerSuiteScript` tag in Preferences header.

=== Fixed in this Release

* Name is null error - When performing an upsert record with a null Name, a NullPointerException would occur. Fixed by properly handling null names.

== 8.2.0

*August 4, 2018*

=== Compatibility

[%header%autowidth.spread]
|===
|Software | Version
|Mule Runtime | 4.0.0 and later
|SuiteTalk API | 2017.2
|===

[NOTE]
The NetSuite version is _not_ the same as the SuiteTalk API version. Your account may run on a version of NetSuite different than the version of the the API you are using.

=== Features

* *Triggers* - You can now start a flow with the NetSuite Connector every time an object of a specific type is created, updated, or deleted.

=== Fixed in this Release

None.

=== Known Issues

None.

== 8.1.1

*July 13, 2018*

=== Compatibility

[%header%autowidth.spread]
|===
|Software | Version
|Mule Runtime | 4.0.0 and later
|SuiteTalk API | 2017.2
|===

[NOTE]
The NetSuite version is _not_ the same as the SuiteTalk API version. Your account may run on a version of NetSuite different than the version of the the API you are using.The NetSuite version is _not_ the same as the SuiteTalk API version. Your account may run on a version of NetSuite different than the version of the the API you are using.

=== Fixed in this Release

* Search operation returned an empty response in Mac and a parsing error in Windows.

=== Known Issues

None.

== 8.1.0

*March 13, 2018*

=== Compatibility

[%header%autowidth.spread]
|===
|Software | Version
|Mule Runtime | 4.0.0 and later
|SuiteTalk API | 2017.2
|===

[NOTE]
The NetSuite version is _not_ the same as the SuiteTalk API version. Your account may run on a version of NetSuite different than the version of the the API you are using.

=== Features

* Support for SuiteTalk API version 2017.2. For a detailed list of changes, log into NetSuite, open Help Center and navigate to New Release > Release Notes > NetSuite 2017.2 Release Notes > SuiteTalk (Web Services) Integration.

== 8.0.0

*November 18, 2017*

=== Compatibility

[%header%autowidth.spread]
|===
|Software | Version
|Mule Runtime | 4.0.0 and later
|SuiteTalk API | 2017.1
|===

The NetSuite version is _not_ the same as the SuiteTalk API version. Your account may run on a version of NetSuite different than the version of the the API you are using.

=== Features

* Support for SuiteTalk API version 2017.1. GA For a detailed list of changes, log into NetSuite, open Help Center and navigate to New Release > Release Notes > NetSuite 2017.1 Release Notes > SuiteTalk (Web Services) Integration.
* Added support for Mule 4.

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
