= Oracle E-Business Suite 12.2 Connector Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: release notes, oracle, ebs, e-business suite, connector

*December 2016*

_Premium_

The Anypoint Connector for *Oracle E-Business Suite (EBS) 12.2* provides real-time connectivity to query and update Oracle EBS using *REST web services*. The connector has been *developed for the Oracle EBS v12.2.x*. For more information about Oracle EBS, visit http://www.oracle.com/us/products/applications/ebusiness/overview/index.html[Oracle's official site].

xref:3.9@mule-runtime::oracle-ebs-122-connector.adoc[Oracle E-Business Suite 12.2 Connector User Guide]

== 1.0.1 - December 28, 2018

=== Compatibility

[width="100%", cols=",", options="header"]
|===
|Software |Version
|Mule Runtime |3.7
|Oracle EBS |12.2.x
|Java | 7
|===

=== Features

None.

=== Fixed in this Release

* *WADL Alias* - Users needed to define the alias of deployed WADLs as their internal names in lowercase. This new version fixes that and this is no longer required.
* *Dynamic metadata* - We detected differences in the responses of the *Rest Service Locator* web service, and the structure of the WADL and XSD files, depending on the patch version of EBS 12.2. This caused problems while fetching and processing dynamic metadata. Our metadata routines were revised and should now work perfectly with all 12.2.x installations.

=== Known Issues

None.


== 1.0.0

*December 22, 2016*

=== Compatibility

[%header%autowidth.spread]
|===
|Software |Version
|Mule Runtime |3.7 and later
|Oracle EBS |12.2.x
|Java | 7
|===

=== Features

* *PL/SQL REST Integration* - The connector provides the functionality to invoke both _standard and user-defined PL/SQL_ functions that are _deployed as REST services_. There is a single processor that takes the alias of a given WADL (REST service endpoint), the name of a service operation available for that WADL and the input parameters required by the selected operation.

== See Also

* For more information about Oracle EBS, visit http://www.oracle.com/us/products/applications/ebusiness/overview/index.html[Oracle's official site]
* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com[Contact MuleSoft Support]
