= Salesforce Connector Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Support Category: Select

== 9.7.1

*May 23, 2019*

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |Mule Enterprise Edition 4.1.1 and later
|Anypoint Studio |7.1.0 and later
|Salesforce |v37.0, v38.0, v39.0, v40.0, v41.0, v42.0, v43.0
|===

=== Fixed in this Release

* Metadata issues for sources - The DataSense keys and output were wrong in the SubscribeTopic, SubscribeChannel, ReplayTopic, and ReplayChannel sources. With this version, the metadata has been fixed. (CONN-1918)
* Duplicate values with objectType case - Issues in the input and output DataSense for different objects where some of the fields were duplicated. (CONN-451)
* Vulnerability reported for Salesforce connector 9.2.2 - Part of the vulnerabilities reported were fixed by upgrading the dependencies the connector uses. (SE-9824)
+
Salesforce connector 9.7.1 now supports these library upgrades:
+
** Jetty `org.eclipse.jetty:jetty-util:9.4.11.v20180605` changed to `org.eclipse.jetty:jetty-util:9.4.17.v20190418`.
** Commons BeanUtils Core (`commons-beanutils:commons-beanutils-core:1.8.3`)
+
NOTE: The BeanShell (`org.beanshell:bsh-core:2.0b4`) and ESAPI (`org.owasp.esapi:esapi:2.1.0.1`) dependencies were removed as they were no longer used.

=== Known Issues

* Batch aggregator with Salesforce Connector executing an upsert operation does not return the right number of failed records when something went wrong. (SE-10501)
* Salesforce connector replayId feature gap between 3.x and 4.x. (SE-11258)
* Salesforce connector autoreplays after restarting the application in CloudHub. (SE-9992)

== 9.7.0

*May 3, 2019*

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |Mule Enterprise Edition 4.1.1 and later
|Anypoint Studio |7.1.0 and later
|Salesforce |v37.0, v38.0, v39.0, v40.0, v41.0, v42.0, v43.0
|===

=== New Features

* Mutual TLS support - Mutual TLS support was added for all the connection providers. (CONN-1142)

=== Fixed in this Release

* Salesforce Subscribe topic connector is disconnected - We have upgraded the CometD library `org.cometd.java:cometd-java-client:3.0.10` to a newer version `org.cometd.java:cometd-java-client:3.1.5` per a Salesforce recommendation, otherwise there might be connectivity issues. Also we have fixed an issue related to "Resume from last replay Id" feature of the Replay Topic and Replay Channel sources where if there were no events for 24 hours and a connection issue appeared, the reconnection stopped working. (SE-11365)
* Salesforce connector memory leak - There was an issue in cached connection providers where some objects could not be cleared properly and this was leading to a memory leak. (CONN-1625)
* Vulnerability reported for Salesforce connector 9.2.2 - A part of the vulnerabilities reported were fixed by upgrading some of the dependencies the connector uses. (SE-9824)
+
Salesforce connector 9.7.0 now supports these library upgrades:
+
** OpenSAML `org.opensaml:opensaml:2.6.4` changed to `org.opensaml:opensaml-core:3.3.0`.
** Commons HTTP Client `commons-httpclient:commons-httpclient:3.1` vulnerability removed as it was part of the OpenSAML dependency.

=== Known Issues

* Batch aggregator with Salesforce Connector executing an upsert operation does not return the right number of failed records when something went wrong. (SE-10501)
* Salesforce connector replayId feature gap between 3.x and 4.x. (SE-11258)
* Salesforce connector autoreplays after restarting the application in CloudHub. (SE-9992)

== 9.6.2

*April 23, 2019*

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |Mule Enterprise Edition 4.1.1 and later
|Anypoint Studio |7.1.0 and later
|Salesforce |v37.0, v38.0, v39.0, v40.0, v41.0, v42.0, v43.0
|===

=== Fixed in this Release

* Salesforce invokes Apex metadata request for each invoke. Now the connector does not fetch all the metadata to validate the connection, it only performs a Get Server Timstamp operation which should tell the app if reconnection is necessary or not. (SE-10925)
* Vulnerability reported for Salesforce connector 9.2.2. A part of the vulnerabilities reported were fixed by upgrading some of the dependencies the connector uses. (SE-9824)
+
Salesforce connector 9.6.2 now supports these library upgrades:
+
** Xalan Java (xalan:xalan:2.7.0) upgraded to 2.7.2
** Apache Commons FileUpload (commons-fileupload:commons-fileupload:1.3.1) upgraded to 1.4
** Xerces (xerces:xercesImpl:2.8.0) upgraded to 2.12.0
** Jackson-Databind (com.fasterxml.jackson.core:jackson-databind:2.9.7) upgraded to 2.9.8
** Apache Commons BeanUtils (commons-beanutils:commons-beanutils:1.7.0) upgraded to 1.9.2
** OWASP AntiSamy (org.owasp.antisamy:antisamy:1.5.3) upgraded to 1.5.8
** Guava: Google Core Libraries for Java (com.google.guava:guava:22.0) upgraded to 27.0.1-jre 

=== Known Issues

* Batch aggregator with Salesforce Connector executing an upsert operation does not return the right number of failed records when something went wrong. (SE-10501)
* Salesforce connector replayId feature gap between 3.x and 4.x. (SE-11258)
* Salesforce connector autoreplays after restarting the application in CloudHub. (SE-9992)


== 9.6.1

*April 11, 2019*

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |Mule Enterprise Edition 4.1.1 and later
|Anypoint Studio |7.1.0 and later
|Salesforce |v37.0, v38.0, v39.0, v40.0, v41.0, v42.0, v43.0
|===

=== Fixed in this Release

* Salesforce definition for a relationship (__r usage) threw error. Fixed an issue regarding object relationships in Salesforce. There was a bug causing troubles when creating objects with custom fields that had relationships to other objects. (SE-10599)
* Salesforce Connector return wrong metadata when include a subquery with a list. Fixed output metadata issues for the query operation when there was a subquery included to retrieve related objects. (SE-10255)
* Subscribe topic operation throws `Invalid SObject Type: null` error. Fixed metadata issues for the Subscribe Topic source. There was an exception thrown when trying to retrieve metadata for different object types. (CONN-1660)
* Salesforce Metadata create order issue. There was an issue with reference fields in input metadata, that now is fixed. (SE-10375)
* Salesforce connector create job bulk v 2 operation content type field is not valid. The only valid content type for this operation is CSV. We could not remove the parameter or the other content types, but the field was moved to the Advanced tab and a proper Summary was added for it. The operation is also fail fast (fails without making an API call) if a type other than CSV is specified. (SE-11043)
* Removed the (Deprecated) keyword in the name of the OAuth 2.0 Connection which was added by mistake in a previous release. The connection was not changed and can be used the same way as up until now.

=== Known Issues

* Salesforce invokes Apex metadata request for each invoke. (SE-10925)
* Batch aggregator with Salesforce Connector executing an upsert operation does not return the right number of failed records when something went wrong. (SE-10501)
* Salesforce connector replayId feature gap between 3.x and 4.x. (SE-11258)
* Salesforce connector autoreplays after restarting the application in CloudHub. (SE-9992)

== 9.6.0

*March 20, 2019*

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |Mule Enterprise Edition 4.1.1 and later
|Anypoint Studio |7.1.0 and later
|Salesforce |v37.0, v38.0, v39.0, v40.0, v41.0, v42.0, v43.0
|===

=== New Features

* Added new versions of connection providers for JWT and SAML, because the existing ones do not match the Salesforce API behavior (one session with the same credentials at a time).
+
To change an existing connection type to the new features, change the XML for the `<salesforce:` element as follows (in essence, add `cached-` after `salesforce:` in your XML configuration):
+
[%header%autowidth.spread]
|===
|Previous Value: | Salesforce v9.6 Value:
|salesforce:basic-connection | salesforce:cached-basic-connection
|salesforce:oauth-jwt-connection | salesforce:cached-oauth-jwt-connection
|salesforce:oauth-saml-connection | salesforce:cached-oauth-saml-connection
|salesforce:oauth-user-pass-connection | salesforce:cached-oauth-user-pass-connection
|salesforce:config-with-oauth-connection | No change
|===
+
IMPORTANT: The OAuth 2.0 connection type is marked as Deprecated in Studio and Design Center, however OAuth 2.0 is still available. The OAuth 2.0 "(Deprecated)" label can be ignored.
+
The previous values are available but are deprecated. We recommend moving to the new versions.

=== Fixed in this Release

* Improved connection performance when executing operations by making better use of the Mule SDK's thread pools.
* Fixed an issue where the connector was unable to handle empty body requests to Apex services.
* Fixed an issue where for the Retrieve operation when the specified ID was invalid the connector was trying to reconnect because of a wrong exception that was thrown.

== 9.5.2

*February 22, 2019*

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |Mule Enterprise Edition 4.1.1 and later
|Anypoint Studio |7.1.0 and later
|Salesforce |v37.0, v38.0, v39.0, v40.0, v41.0, v42.0, v43
|===

=== Fixed in this Release

* Metadata for Apex classes didn't work if an instance had more than 200 records. Fixed by using the search service to query the instance for Apex classes instead of a simple query.
* Null values were set as blank by DataWeave when obtained from the Salesforce Connector. Fixed by changing the returning JSONObject.NULL fields to null.
* Improved the API call that validates the connection to improve connector performance.

== 9.5.1

*February 14, 2019*

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |Mule Enterprise Edition 4.1.1 and later
|Anypoint Studio |7.1.0 and later
|Salesforce |v37.0, v38.0, v39.0, v40.0, v41.0, v42.0, v43
|===

=== Fixed in this Release

* Invalid Session ID and Reconnection Strategy works only after multiple invalid requests when this connector performs a concurrent query. Fixed by implementing a new CachedOauthUserPassConnectionProvider with keep-alive functionality.
* GetSessionId was not returning the correct ID after the session was invalidated, because it was not throwing the correct exception. This was fixed by adding a call to the API, that returns a ConnectionException if the session ID is invalid
* The operation "Create Content Version" was failing if the payload was of binary data type. This was fixed by checking the data type before casting to String, so no exception is thrown
* Apex method call recognized an output field as a date if the return string has a similar format as Date. Methods in Apex come with a return type parameter which is now included in the condition which converts a string to a date type.
* Invoking Apex REST was not reconnecting when a session expired. Fixed by properly handling exceptions thrown by the Apex API.
* Fixed problem that occurred when attempting to create a new Content Version that had data as a Base64 format picture, it is not required to decode the Base64 string since the decoding is handled by the connector. 
+
This also impacts SE-9518, this fix is deprecated. Users that have VersionData that is not Base64 must ensure that they convert it to Base64, for example: `VersionData:toBase64(payload)`
+
In short, VersionData for the Version Content expects a Base64 format.

== 9.5.0

*February 1, 2019*

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |Mule Enterprise Edition 4.1.1 and later
|Anypoint Studio |7.1.0 and later
|Salesforce |v37.0, v38.0, v39.0, v40.0, v41.0, v42.0, v43
|===

=== Fixed in this Release

* The clearNullFields config parameter was not used properly and its functionality would have never worked. Fixed the way clearNullFields is handled and now works as intended.
* Fixed Salesforce Connector not reconnecting when a Bulk operation session expired. Fixed by changing the exception thrown in this case.
* Retrieve record failure Bulk v2 not failing because of column delimiter. Fixed by adding handling for a column delimiter for the retrieve record failure Bulk v2.
* Invalid Session ID and Reconnection Strategy works only after multiple invalid requests when the Mule connector performs a concurrent query. Fixed by implementing a new CachedBasicConnectionProvider with keep-alive functionality. 
* The BasicConnectionProvider was deprecated because a PoolingConnectionProvider does not have sense in the context of Salesforce's way of handling multiple logins, which returns the same sessionId.
* Username Password connection provider was improved by handling invalid connections currently in the pool, so before executing an operation, the connector ensures that the operation uses a valid connection.

== 9.4.8

*December 12, 2018*

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |Mule Enterprise Edition 4.1.1 and later
|Anypoint Studio |7.1.0 and later
|Salesforce |v37.0, v38.0, v39.0, v40.0, v41.0, v42.0, v43
|===

=== Fixed in this Release

* Fixed an issue on the Replay Streaming Channel where the source stopped working and receiving messages after 48 hours. Fixed by handling the DISCONNECTED state of SalesforceBayeuxClient.

== 9.4.7

*December 7, 2018*

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime |Mule Enterprise Edition 4.1.1 and later
|Anypoint Studio |7.1.0 and later
|Salesforce |v37.0, v38.0, v39.0, v40.0, v41.0, v42.0, v43
|===

=== Fixed in this Release

* Fixed an issue on the Create operation that was not returning the DuplicateResults when there was a duplicate record in the Salesforce instance.
Now if the "includeRecordDetails" header is specified, the operation returns the details about the duplicate entities.

== 9.4.6

*November 28, 2018*

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime |Mule Enterprise Edition 4.1.1 and later
|Anypoint Studio |7.1.0 and later
|Salesforce |v37.0, v38.0, v39.0, v40.0, v41.0, v42.0, v43
|===

=== Fixed in this Release

* Fixed an issue on Query operation where the connector was not able to reconnect after the session became invalid
* The Query operation was not handling properly the exceptions thrown by the Salesforce API.

== 9.4.5

*November 14, 2018*

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |Mule Enterprise Edition 4.1.1 and later
|Anypoint Studio |7.1.0 and later
|Salesforce |v37.0, v38.0, v39.0, v40.0, v41.0, v42.0, v43
|===

=== Fixed in this Release

* Fixed security issues regarding libraries. 

== 9.4.4

*November 14, 2018*

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |Mule Enterprise Edition 4.1.1 and later
|Anypoint Studio |7.1.0 and later
|Salesforce |v37.0, v38.0, v39.0, v40.0, v41.0, v42.0, v43
|===

=== Fixed in this Release

* Fixed an issue in the Read Metadata operation where the connector was unable to return picklist values.
* Fixed the problem of error message mapping in the Create Bulk v2 operation.

== 9.4.3

*November 9, 2018*

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |Mule Enterprise Edition 4.1.1 and later
|Anypoint Studio |7.1.0 and later
|Salesforce |v37.0, v38.0, v39.0, v40.0, v41.0, v42.0, v43
|===

=== Fixed in this Release

* Fixed an issue in the Create Batch Stream operation where the connector was not able to reconnect after the session became invalid.
* Fixed an issue in the Query operations where the execution was stopping if the query was invalid. Now a proper error is raised.

== 9.4.2

*October 29, 2018*

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |Mule Enterprise Edition 4.1.1 and later
|Anypoint Studio |Studio 7.1.0 and later
|Salesforce |v37.0, v38.0, v39.0, v40.0, v41.0, v42.0, v43
|===

=== Fixed in this Release

* Fixed mapping for DescribeSObject.

== 9.4.1

*October 8, 2018*

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |Mule Enterprise Edition 4.1.1 and later
|Anypoint Studio |7.1.0 and later
|Salesforce |v37.0, v38.0, v39.0, v40.0, v41.0, v42.0, v43
|===

=== Fixed in this Release

* Added missing metadata types on Metadata operations.


== 9.4.0

*September 24, 2018*

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |Mule Enterprise Edition 4.1.1 and later
|Anypoint Studio |7.1.0 and later
|Salesforce |v37.0, v38.0, v39.0, v40.0, v41.0, v42.0, v43
|===

=== Features

Added support for Salesforce V43.

== 9.3.5

*October 22, 2018*

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |Mule Enterprise Edition 4.1.1 and later
|Anypoint Studio |7.1.0 and later
|Salesforce |v37.0, v38.0, v39.0, v40.0, v41.0, v42.0
|===

=== Fixed in this Release

* Fixed an issue where the connector Attachments were not supporting base64 encoded body.
* Fixed an issue on create ContentVersion object that was failing because the Content Data field was not serialized properly.
* Fixed an issue for the Batch info list, Batch info, and Job info operations that were going into an infinite loop because they were defaulting to XML content type. Optional parameters were added so the user can specify the content type for the entity so that it will not fail any more.

== 9.3.4

*October 8, 2018*

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |Mule Enterprise Edition 4.1.1 and later
|Anypoint Studio |7.1.0 and later
|Salesforce |v37.0, v38.0, v39.0, v40.0, v41.0, v42.0
|===

=== Fixed in this Release

* Added missing metadata types on Metadata operations.

== 9.3.3

*September 19, 2018*

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |Mule Enterprise Edition 4.1.1 and later
|Anypoint Studio |7.1.0 and later
|Salesforce |v37.0, v38.0, v39.0, v40.0, v41.0, v42.0
|===

=== Fixed in this Release

* Get updated objects failed with UNKNOWN error when no records were retrieved. This is no longer the case.

* CustomObjectTranslation was not working for the Read Metadata operation. This was fixed.

== 9.3.2

*August 30, 2018*

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |Mule Enterprise Edition 4.1.1 and later
|Anypoint Studio |7.1.0 and later
|Salesforce |v37.0, v38.0, v39.0, v40.0, v41.0
|===

=== Fixed in this Release

* Getting NullPointerException while retrieving input metadata when describing reference type objects:

[source,text,linenums]
----
org.mule.runtime.api.metadata.MetadataResolvingException: Unable to resolve metadata for: Account
Caused by: java.lang.NullPointerException: Request headers cannot be null.
----

The problem was solved by reimplementing the metadata parsing for reference type objects.

* Customers saw this intermittent exception:

[source,text,linenums]
----
[UnexpectedErrorFault [ApiFault  exceptionCode='INVALID_SESSION_ID'
exceptionMessage='Invalid Session ID found in SessionHeader: Illegal Session. 
Session not found, missing session hash: <hash>
This error usually occurs after a session expires or a user logs out.'
----

The problem was solved by adding missing error handling for reconnection due to invalid session.

== 9.3.1

*August 1, 2018*

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |Mule Enterprise Edition 4.1.1 and later
|Anypoint Studio |7.1.0 and later
|Salesforce |v37.0, v38.0, v39.0, v40.0, v41.0, v42.0
|===

=== Fixed in this Release

Salesforce connector disconnects and never connects back again. The issue was fixed by making changes in the Reconnection Strategy.


== 9.3.0

*July 26, 2018*

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |Mule Enterprise Edition 4.1.1 and later
|Anypoint Studio |7.1.0 and later
|Salesforce |v37.0, v38.0, v39.0, v40.0, v41.0, v42.0
|===

=== Features

* Update the connector to support Salesforce Spring 2018 (API v42)

* Support Bulk API v2

=== Fixed in this Release

* After a time that the connector was not being used, customers got the following error:
+
[source,text,linenums]
----
Root Exception stack trace:
[UnexpectedErrorFault [ApiFault exceptionCode='INVALID_SESSION_ID'
exceptionMessage='Invalid Session ID found in SessionHeader: Illegal Session. Session not found, missing session hash: jiVw2Gqdz4jdt5QfJJcVLbEHzg4NFOAPHpWosGrWyUA=
This error usually occurs after a session expires or a user logs out.'
----
+
The problem was solved by reimplementing reconnection strategy for paginating queries.
+
* The customer couldn't make APEX call without parameters.
+
The problem was solved by making APEX methods to access the objects without using them as parameters.
+
* The customer couldn't make APEX call without parameters with array payload.
+
The problem was solved by treated the lists of parameters separately.
+
* When using the Salesforce connector inside a batch job that uses the Batch Aggregator with the Upsert operation, the records were not being marked as failed or successful because the result was not being returned as BulkOperationResult.
+
The problem was solved by adding 4 new operations for create, update, upsert, and delete that return BulkOperationResult.

== 9.2.2

*June 28, 2018*

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |Mule Enterprise Edition 4.1.1 and later
|Anypoint Studio |7.1.0 and later
|Salesforce |v37.0, v38.0, v39.0, v40.0, v41.0
|===

=== Fixed in this Release

* When making a call to a Salesforce Apex method, if the method didn't have a parameter, Salesforce connector did not pass the flow payload to the Apex method. Now, the connector passes the flow payload.

== 9.2.1

*May 18, 2018*

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |Mule Enterprise Edition 4.1.1 and later
|Anypoint Studio |7.1.0 and later
|Salesforce |v37.0, v38.0, v39.0, v40.0, v41.0
|===

=== Fixed in this Release

* Salesforce connector was not working in EU.  When using Salesforce Connector in EU, it threw this exception:
+
[source,text,linenums]
----
Caused by: org.springframework.beans.factory.BeanCreationException:
Could not autowire field: private org.mule.runtime.api.store.ObjectStoreManager
org.mule.extension.salesforce.internal.operation.UtilityOperations.objectStoreManager;
nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException:
No qualifying bean of type [org.mule.runtime.api.store.ObjectStoreManager] is defined:
expected single matching bean but found 2: _muleObjectStoreManager,_muleLocalObjectStoreManager
----
+
In this version Salesforce Connector works correctly in EU.

== 9.2.0

*May 2, 2018*

=== Compatibility

Salesforce connector version 9.2.0 is compatible with:

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |Mule Enterprise Edition 4.1.0 and later
|Anypoint Studio |7.1.0 and later
|Salesforce |v37.0, v38.0, v39.0, v40.0, v41.0
|===

=== Features

* Changed Minimum Mule Version to 4.1.1.

== 9.1.2

*May 18, 2018*

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |Mule Enterprise Edition 4.1.0 and later
|Anypoint Studio |7.1.0 and later
|Salesforce |v37.0, v38.0, v39.0, v40.0, v41.0
|===

=== Fixed in this Release

* Salesforce connector was not working in EU.  When using Salesforce Connector in EU, it threw this exception:
+
[source,text,linenums]
----
Caused by: org.springframework.beans.factory.BeanCreationException:
Could not autowire field: private org.mule.runtime.api.store.ObjectStoreManager
org.mule.extension.salesforce.internal.operation.UtilityOperations.objectStoreManager;
nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException:
No qualifying bean of type [org.mule.runtime.api.store.ObjectStoreManager] is defined:
expected single matching bean but found 2: _muleObjectStoreManager,_muleLocalObjectStoreManager
----
+
In this version Salesforce Connector works correctly in EU.

== 9.1.1

*May 2, 2018*

=== Compatibility

Salesforce connector version 9.1.1 is compatible with:

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |Mule Enterprise Edition 4.1.0 and later
|Anypoint Studio |7.1.0 and later
|Salesforce |v37.0, v38.0, v39.0, v40.0, v41.0
|===

=== Features

* Added the isForceResubscribe method in Salesforce Bayeux Client.
* Support for Anypoint Studio Proxy configuration as the default.

=== Fixed in this Release

 * Trigger operation did not retrieve MetadataKeysId. Solved by adding support for retrieving metadata in case of sources.
 * Reply topic was losing messages in case the connection has been lost for less than 40 seconds; this is the amount of time that was needed to trigger re-subscribe naturally according to Salesforce documentation. The issue was solved by forcing re-subscription whenever the network connection is lost.
 * Buffering capacity exceeded message was triggered when the connector consumed more than 10000 messages from a topic. The issue was solved by adding a new attribute for the "Replay streaming channel" operation: Buffer Size In Bytes, it's an optional parameter with the default value of 26 MB.
 * Wrong transformation of fields of type Date. Trying to update or insert an Object in Salesforce with fields of type Date caused a failure, this was due to failure in serializing the objects of type Date. The issue was solved by parsing the values received from the Mule flow and converting them into the expected Salesforce accepted format.

== 9.1.0

*February 21, 2018*

This release adds new features.

=== Compatibility

Salesforce connector version 9.1.0 is compatible with:

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |Mule Enterprise Edition 4.1.0
|Anypoint Studio |7.0.0 and later
|Salesforce |v37.0, v38.0, v39.0, v40.0, v41.0
|===

=== Features

* Support for new and changed objects in metadata - API v41.
* Support for defining any absolute path for the keystore.
* Salesforce trigger - To address ad-hoc integrators or citizen integrators with Design Center, you can now start a flow with the Salesforce connector when
you create an object. For example, when new data is added to a lead object
or an opportunity object, you now have an easier way to initiate a flow.

=== Fixed in this Release

* Query with parameters didn't work.

== See Also

* xref:connectors::salesforce/salesforce-connector.adoc[Salesforce Connector Guide]
* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
