= SharePoint Connector Release Notes - Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Support Category: Select

The Anypoint Connector for SharePoint lets you connect to the Microsoft SharePoint application. The connector exposes convenient methods to work with Microsoft SharePoint API.

== 3.1.3

*July 17, 2019*

=== Compatibility

The SharePoint connector is compatible with:

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime|Mule Enterprise Edition 4.0.0 and later
|Anypoint Studio|Studio 7.0.0 and later
|===

=== Features

* An optional parameter named *Path* is now available for the *Created objects* and *Modified objects* triggers. Use this parameter to specify the root path to start querying for when the object type is `FILE` or `FOLDER`. The *Path* parameter is ignored for other object types.
 
* The default value for the *Since* field of the *Created objects*, *Modified objects* and *Deleted objects* triggers now formats the current time in UTC format rather than defaulting to the time on the machine running the Mule application.

=== Fixed in this Release

*  Sharepoint connector: Not possible to use $top parameter for retrieve-collection. (SE-12212)

== 3.1.2

*July 2, 2019*

=== Compatibility

The SharePoint connector is compatible with:

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime|Mule Enterprise Edition 4.0.0 and later
|Anypoint Studio|Studio 7.0.0 and later
|===

=== Fixed in this Release

*  Error produced when using a payload with é (e with accent) in the connector. (SE-11852)

== 3.1.1

*October 5, 2018*

=== Compatibility

The SharePoint connector is compatible with:

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime|Mule Enterprise Edition 4.0.0 and later
|Anypoint Studio|Studio 7.0.0 and later
|===

=== Fixed in this Release

*  When doing a Select Item Query the connector threw NullPointerException.
The problem was solved by parsing the query provided by the client.

== 3.1.0 

*May 10, 2018*

The Sharepoint connector is compatible with:

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime|Mule Enterprise Edition 4.1.1 and later
|Anypoint Studio|Studio 7.0.0 and later
|===

=== Features:

* Implemented triggers for created, deleted and updated objects. The triggers are New Objects Trigger, Deleted Objects Trigger, Modified Objects Trigger.

== 3.0.0

*January 19, 2018*

=== Compatibility

The SharePoint connector is compatible with:

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime|Mule Enterprise Edition 4.0.0 and later
|Anypoint Studio|Studio 7.0.0 and later
|===

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
