= Workday Connector Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Support Category: Select

Workday is a software as a service (SaaS) solution developed by Workday comprising of a set of management applications that cover areas such as human resources management, staffing, recruiting, and performance management.

The Workday connector requires an Enterprise license.

[IMPORTANT]
Depending on the connectivity conditions while using Workday connector in Anypoint Studio, there can be a timeout while obtaning Workday metadata. See xref:connectors::workday/workday-studio.adoc#to-increase-timeout-in-studio[To Increase Timeout in Studio].

== 10.0.1

*Date of the release TBD*

This release provides a bug fix.


[%header%autowidth.spread]
|===
|Software |Version
|Mule Runtime |4.0.0 and later
|Workday API |v28.0, v29.0, v30.0
|===

=== Fixed in this Release

Connector had connectivity issue when Workday password contained special characters e.g.(< > & ") . This issue has been fixed  [SE-12090]

== 10.0.0

*November 9, 2018*

[%header%autowidth.spread]
|===
|Software |Version
|Mule Runtime |4.0.0 and later
|Workday API |v28.0, v29.0, v30.0
|===

=== Features

* This connector now supports multiple versions of the Workday API.
* New Object Trigger - You can now start a flow with the connector every time an object of a specific type is created.

=== Fixed in this Release

None.

== 9.2.0

*March 15, 2018*

This release provides a bug fix.

[%header%autowidth.spread]
|===
|Software |Version
|Mule Runtime |4.0.0 and later
|Workday API |v29.1
|===

=== Fixed in this Release

Fixed test connectivity.

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
