= X12 Connectors Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Support Category: Premium

== 1.3.4

*April 2019*

=== Fixed in this Release

* Added support for integer value types for implied decimal format. (SE-11494)
* Multiple HIPAA transaction sets in a group are now correctly handled. (SE-9043)
* Identified the ISA segment when it’s the cause of a write error. (SE-10796)
* Changed the shaded package name for debugger compatibility. (SE-10796)
* Added the transaction set information to the error message for 'schema not found'. (SE-7935)

=== Compatibility

[%header,cols="30a,70a"]
|===
|Application or Service |Version
|Mule Runtime |Mule 3.6.0 and later
|X12 |003010, 003020, 003030, 003040, 003050, 003060, 003070, 004010, 004020, 004030, 004040, 004050, 004060, 005010, 005020, 005030, 005040, 005050, and 006020
|HIPAA |005010X212, 005010X214B3, 005010X217, 005010X218, 005010X220A1, 005010X221A1, 005010X222A1, 005010X222A2, 005010X223A2, 005010X223A3, 005010X224A2, 005010X224A3, and 005010X279A1
|===

== 1.3.2

*August 3, 2018*

This release adds support for HIPAA X222A1 and X224A2 837 transaction sets.

=== Compatibility

X12 EDI Connector v1.3.2 is compatible with the following:

[%header,cols="30a,70a"]
|===
|Application/Service |Version
|Mule Runtime |Mule 3.6.0 and later
|X12 |003010, 003020, 003030, 003040, 003050, 003060, 003070, 004010, 004020, 004030, 004040, 004050, 004060, 005010, 005020, 005030, 005040, 005050, and 006020
|HIPAA |005010X212, 005010X214B3, 005010X217, 005010X218, 005010X220A1, 005010X221A1, 005010X222A1, 005010X222A2, 005010X223A2, 005010X223A3, 005010X224A2, 005010X224A3, and 005010X279A1
|===


== 1.3.1

*January 19, 2018*

=== Compatibility

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime|Mule 3.6.0 and later
|===

=== Fixed Issues

* X12 corrected the schema version from 005010X214B3 to 005010X214.

=== New Features

* X12 added HIPAA 005010X223A2 support.

== 1.3.0

*November 7, 2017*

===  Compatibility

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime|Mule 3.6.0 and later
|===

=== Fixed Issues

* X12 corrected an error in formatting values for the ISA10 and GS05 time fields.
* X12 corrected a serialization-related error causing an exception scala.MatchError: None.

=== New Features

* X12 HIPAA support, including Type 1 and 2 validation.
* X12 error reporting - added information for error type (interchange, group, transaction, segment, or element) and interchange/group/transaction set identifiers; all error reports now included in the root level map.
* X12 now includes all versions from 003010 to 005050, and 006020.
* X12 added validateBeforeWrite configuration parameter to check for errors in data before writing to the output stream, instead of checking while the data is being written; if one or more fatal errors are found an exception is thrown from the write operation without any data being written.
* X12 added ackAllSets configuration parameter to generate a separate AK2/AK5 (997) or AK2/IK5 (999) acknowledgment for every transaction set; by default, only transaction sets with errors are specified in the acknowledgment.

== 1.2.2

*December 27, 2016*

=== Compatibility

[%header,cols="50,50"]
|===
|Application/Service|Version
|Mule Runtime|Mule 3.6.0 and newer
|===

=== Fixed Issues

* Supports '\n' as a segmentTerminator.

== 1.2.1

*September 28, 2016*

=== Compatibility

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime|Mule 3.6.0 and later
|===

===  New Features

* Added support for inline components in ESL schema definitions.
* Added support for writing DataWeave-compatible types.
* Improved overlay handling, allowing segments to specify only modified components and change component type
* Support writing repeating composite.
* Add interchange information (with sender and receiver reversed) to X12 TA1 interchange acknowledgments generated by parsing.
* Support sending X12 messages with only TA1 interchange acknowledgments, no transaction data.

=== Fixed Issues

* Corrected some off-by-one errors in reporting data errors.
* Changed loop keys in data, eliminating position numbers previously used at start of key.
* Corrected loop position tracking and reporting in X12 ACK3/IK3, ACK4/IK4 segments (997/999 functional acknowledgments).
* Correct check for data present when reading a composite to work correctly when first value of composite is empty.

== 1.0.2

*March 9, 2016*

=== Compatibility

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime|Mule 3.6.0 and later
|===

=== New Features

* Add more details to error logging.

=== Fixed Issues

* Changed identifiers for X12 loops with numeric values as names, using the number as part of the identifier (rather than the identifier of the first segment in the loop).
* Correct handling of X12 repeating group inside LS/LE wrapper.
* Fix issue causing X12 parser IllegalStateException "Illegal structure at position...".

== 1.0.1

*November 10, 2015*

=== Compatibility

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime|Mule 3.6.0 and later
|===

=== New in This Release

This release contains the following fixes:

* Fixed dead lock when acquiring lock to increment control number
* Writing now correctly fails when writing invalid characters and repeating values outside defined limits
* New icons for the connector

For more information, such as how to install or use these modules, see
xref:partner-manager::index.adoc[Anypoint B2B], xref:partner-manager::edifact-module.adoc[EDIFACT Module], and xref:partner-manager::x12-module.adoc[X12 Module].

=== Migration Guide

No application changes are needed from 1.0.0.


== 1.0.0

*Sept 21, 2015*

=== Compatibility

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime|Mule 3.6.0 and later
|===


=== New in This Release

This release contains many improvements, including:

* Support for reading/writing multiple versions of the same transaction type within a single message
* Improved structure usability with DataWeave and MEL by including "Loop" in the key name for loops and using underscores instead of spaces. You will need to update your integrations appropriately for this (see below).
* Improved validation logic on writing.
* Many bug fixes

For more information, such as how to install or use these modules, see
xref:partner-manager::index.adoc[Anypoint B2B], xref:partner-manager::edifact-module.adoc[EDIFACT Module], and xref:partner-manager::x12-module.adoc[X12 Module].

=== Migration Guide

All of your transformations and expressions that references parts of the EDI message structure must be updated for the following changes:

* The "Transactions" list has been changed to "TransactionSets" and now has an additional level for the version of the transactions.
** Example: payload.Transactions."850" now becomes payload.TransactionSets.v5010."850"
* All keys no longer have spaces - instead they have underscores
** Example: payload."0100 PO1" becomes payload."0100_PO1"
* Any segment that is a loop
** Example: payload.Detail."0100 PO1" becomes payload.Detail."0100_PO1_Loop"

== Known Issues

The following issues apply to all versions:

* X12 binary segments are not supported, are not included in schema definitions, and cause errors.
* Code values are not currently verified for either reading or writing. (as of version 1.3.0, X12 HIPAA validation supports mandated code values)
* X12 syntax rules are not currently enforced for either reading or writing. (as of version 1.3.0, X12 HIPAA validation supports syntax rules)

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
