= Rate Limiting Policy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: mule, rate-limit, policy, release notes


== 1.3.1

*Jul 12, 2019*

=== Minimum Mule Version

*Mule 4.1.0*

=== New Features and Enhancements

* Several performance improvements were introduced in this release.


== 1.3.0

*Apr 26, 2018*

=== Minimum Mule Version

*Mule 4.1.0*

=== New Features and Enhancements

* Unless explicitly configured, by checking the "Expose headers" option, the policy header will not be propagated or returned. The default configuration is modified to support this behaviour.
* Several performance improvements were introduced in this release.

=== Fixed Issues

* The persistence scheduler was losing quota in a Mule Cluster when the node's clocks were out-of-sync. This error is now resolved.


== 1.2.3

*Feb 14, 2019*

=== Minimum Mule Version

*Mule 4.1.0*

=== Fixed Issues

* Fixed `NullPointerException` thrown when disposing policy in a Mule Cluster.


== 1.2.2

*Oct 17, 2018*

=== Minimum Mule Version

*Mule 4.1.0*

=== Fixed Issues

* Resolved the WSDL error response issue.
* An object store error occurred when hitting the API concurrently. This error is now resolved.
* Optimized throttling connector performance.
* An `ExpressionRuntimeException` error occurred when a WSDL proxy received an empty payload, or an invalid XML. This error is now resolved.


== 1.2.1

*Jun 25, 2018*

=== Minimum Mule Version

*Mule 4.1.0*

=== New Features and Enhancements

* Added 'violationCategory' in the YAML configuration file for Feedback Loop.

=== Fixed Issues

* If an extension set authentication using an Authentication object containing null properties, a `NullPointerException` error occurred. This error is now resolved.


== 1.2.0

*Mar 22, 2018*

=== Minimum Mule Version

*Mule 4.1.0*

=== New Features and Enhancements

* Parameterized throttling algorithm introduced for Mule 4.
* Migrated pluggable Hazelcast to 4.x.

=== Fixed Issues

* The Rate Limiting policy was rejected from scheduler during high network traffic. This error is now resolved.


== 1.1.0

*Jan 25, 2018*

=== Minimum Mule Version

*4.1.0*

=== New Features and Enhancements

* Updated `WWW-Authenticate` header value from `mule-real` to `Client-ID-Enforcement`.
* Reduced error-handling verbosity in templates.

=== Fixed Issues

* An `ExpressionRuntimeException` error occurred when a WSDL proxy received an empty payload, or an invalid XML. This error is now resolved.


== 1.0.0

*Nov 14, 2017*

=== Minimum Mule Version

*4.0.0*

== See Also

* xref:api-manager::rate-limiting-and-throttling.adoc[Rate Limit for Mule 4]
