= Rate Limiting SLA Policy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: mule, rate-limit, policy, release notes


== 1.2.2

*Jul 12, 2019*

=== Minimum Mule Version

*Mule 4.1.0*

=== New Features and Enhancements

* Several performance improvements were introduced in this release.

=== Fixed Issues

* The persistence scheduler was losing quota in a Mule Cluster when the node's clocks were out-of-sync. This error is not resolved.


== 1.2.1

*Apr 30, 2019*

=== Minimum Mule Version

*Mule 4.1.0*

=== Fixed Issues

* An error occurred when multiple client applications using one rate limiting algorithm were configured with the same SLA in Anypoint Platform. This error is now resolved.


== 1.2.0

*Apr 26, 2019*

=== Minimum Mule Version

*Mule 4.1.0*

=== New Features and Enhancements

* Unless explicitly configured, by checking the "Expose headers" option, the policy header will not be propagated or returned. The default configuration is modified to support this behaviour.
* Several performance improvements were introduced in this release.


== 1.1.3

*Feb 14, 2019*

=== Minimum Mule Version

*Mule 4.1.0*

=== Fixed Issues

* Fixed `NullPointerException` thrown when disposing policy in a Mule Cluster.


== 1.1.2

*Jan 10, 2019*

=== Minimum Mule Version

*Mule 4.1.0*

=== New Features and Enhancements

* Improved the RAML and OAS snippets.


== 1.1.1

*Jun 25, 2018*

=== Minimum Mule Version

*Mule 4.1.0*

=== New Features and Enhancements

* Migrated pluggable Hazelcast to 4.x.

=== Fixed Issues

* The Rate Limiting policy was rejected from scheduler during high network traffic. This error is now resolved.
* An `ExpressionRuntimeException` error occurred when a WSDL proxy received an empty payload, or an invalid XML. This error is now resolved.
* If an extension set authentication using an Authentication object containing null properties, a `NullPointerException` error occurred. This error is now resolved.


== 1.1.0

*Jan 25, 2018*

=== Minimum Mule Version

*4.1.0*

=== New Features and Enhancements

* Changed `WWW-Authenticate` header value from `mule-real` to `Client-ID-Enforcement`.
* Reduced error-handling verbosity in templates.

=== Fixed Issues

* An `ExpressionRuntimeException` error occurred when a WSDL proxy received an empty payload, or an invalid XML. This error is now resolved.


== 1.0.0

*Nov 14, 2017*

=== Minimum Mule Version

*4.0.0*

== See Also

* xref:api-manager::rate-limiting-and-throttling.adoc[Rate Limit for Mule 4]
