= Anypoint Monitoring Installer Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: release notes, cloudhub, cloud hub

These release notes are for patches made to the Anypoint Monitoring agent installer. In addition to these release notes, see:

* xref:monitoring/anypoint-monitoring-release-notes.adoc[Anypoint Monitoring Release Notes] 
* xref:monitoring::am-installing#update-the-monitoring-agent.adoc[Update the Monitoring Agent]
* xref:monitoring::index.adoc[Anypoint Monitoring]

[NOTE]
If you update the Runtime Manager agent, you must execute the Anypoint Monitoring agent uninstall script and then re-install the Anypoint Monitoring agent. 

== March 26, 2019

2.1.0.0 Anypoint Monitoring agent installer update:

This release includes support for the SOCKS5 proxy. For more information, see xref:monitoring::am-installing.adoc[Install Anypoint Monitoring On-Premises].

You can download the Anypoint Monitoring agent installer from https://s3.amazonaws.com/cdn-anypoint-prod/artifacts/monitoring-center-ui/app/hybrid/am-2.1.0.0.zip[Anypoint Monitoring Agent Installer 2.1.0.0] or from the Anypoint Monitoring *Settings > Hybrid* page. 

== February 13, 2019

2.0.5.0 Anypoint Monitoring agent installer update:

* Added metrics for operating system
* Added support for the following versions of Mule Runtime Manager agent:
** 1.11.x
** 1.12.x
** 2.2.x

You can download the Anypoint Monitoring agent installer from https://s3.amazonaws.com/cdn-anypoint-prod/artifacts/monitoring-center-ui/app/hybrid/am-2.0.5.0.zip[Anypoint Monitoring Agent Installer 2.0.5.0]

== February 11, 2019

2.0.4.0 Anypoint Monitoring agent installer update:

* Added support for Mule Runtime Manager agent version 2.1.8.
* Added support for Mule runtime engine version 4.1.5.

