= Anypoint Monitoring Installer Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: release notes, cloudhub, cloud hub

These are the release notes for patches which are made to the Anypoint Monitoring hybrid installer and agent . In addition to these release notes, see the xref:monitoring/anypoint-monitoring-release-notes.adoc[Anypoint Monitoring Release Notes] and the complete xref:monitoring::index.adoc[Anypoint Monitoring] documentation.

[NOTE]
If you update the Runtime Manager agent, you must execute the Anypoint Monitoring agent uninstall script and then re-install the Anypoint Monitoring agent. 

== February 13, 2019

2.0.5.0 Anypoint Monitoring installer update:

* Added metrics for operating system
* Added support for the following versions of Mule Runtime Manager agent:
** 1.11.x
** 1.12.x
** 2.2.x

You can download the Anypoint Monitoring installer from the following URLs:

* https://s3.amazonaws.com/cdn-anypoint-prod/artifacts/monitoring-center-ui/app/hybrid/am-2.0.5.0.zip
* (Europe) https://s3.eu-central-1.amazonaws.com/cdn-anypoint-prod-eu/artifacts/monitoring-center-ui/app/hybrid/am-2.0.5.0.zip

== February 11, 2019

2.0.4.0 Anypoint Monitoring installer update:

* Added support for Mule Runtime Manager agent version 2.1.8.
* Added support for Mule runtime engine version 4.1.5.

