= Anypoint Monitoring Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

This document describes any new features and enhancements, known limitations, issues, and fixes in Anypoint Monitoring.

== Version 2.1

=== New Features
December 15, 2018

* *API Analytics* - API Analytics is now available in Anypoint Monitoring. See xref:monitoring::api-analytics-dashboard.adoc[Builtin API Analytics Dashboard].
* *Anypoint Custom Metrics Connector* - (Requires a Titanium subscription) The Anypoint Custom Metrics connector enables sending metric values with dimensions to Anypoint Monitoring, where they can be visualized in real time using Custom Dashboards. See xref:connectors::metrics/custom-metrics-connector.adoc[Custom Metrics Connector].

=== New Features
December 8, 2018

* *Log Points* - (Requires Titanium subscription) You can generate logs for a running API without writing any code or redeploying your application. You can select specific parameters within the API for which to generate logs, for example, the request header `host` parameter. For more information about log points, see xref:monitoring::log-points.adoc[Anypoint Monitoring Log Points]
* *Connector-level Flow Analysis* - (Requires Titanium subscription) You can now monitor the performance for connectors. For more information about monitoring connectors, see xref:monitoring::monitor-connectors.adoc[Monitor Connectors]


=== Known Issues

The Anypoint Monitoring log points feature is only supported on Mule runtime engine version 3.8.5-AM or later. For APIs not running on Mule runtime engine 3.8.5-AM or later, the log points feature does not appear for the API.

Since you can't select the runtime version when you deploy an API from API Manager, you need to navigate to Runtime Manager, select the runtime version (3.8.5-AM or later), then redeploy the API.

[NOTE]
Mule runtime engine versions appended with `-AM` are listed in Runtime Manager, in the *Runtime Version* menu under *Show old patch releases*. 

=== Fixed Issues

* General bug fixes.


== Version 1.05

=== New Features and Enhancements

* Environment-wide reporting on application performance, including requests, failures, CPU and memory utilization. (Requires a Titanium subscription)
* Performance Improvements
** All static resources are stored on a content delivery network (CDN).
** Resources are prefetched on page load.
** Changes to built-in dashboards load more quickly.
** Extended connection pools life before timeout.
* Improvements to Deployment and Management:
** New capabilities to associate an Organization with an environment so that you can build proofs of concept (POCs) without relying on engineering work.
** Provisioning Configuration Management: Allows for changes to the data sources without requiring a new deployment. Versioning to allow controlled roll out.
** Log Orchestration Service updates periodically from the Provisioning System: allows the creation of an Organization log index without requiring a deployment.
** Admin console now exposes data from Provisioning: it allows easier visualization and editing of the environment properties.
* Minor user experience (UX) improvements.
* Log search share URL.

=== Fixed Issues

* General bug fixes.
