= Anypoint Monitoring Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

This document describes any new features and enhancements, known limitations, issues, and fixes in Anypoint Monitoring.

== Version 2.1

=== New Features

* *Log Points* - (Requires Titanium subscription) You can generate logs for a running API without writing any code or redeploying your application. You can select specific parameters within the API for which to generate logs, for example, the request header host parameter. For more information about log points, see xref:/monitoring/log-points.adoc[Anypoint Monitoring Log Points]
* *Flow Pinpoint Map* - (Requires Titanium subscription) You can now monitor the performance for connectors. For more information about monitoring connectors, see xref:/monitoring/monitor-connectors.adoc[Monitor Connectors]
* *API Analytics* - API Analytics is now available in Anypoint Monitoring. See xref:/monitoring/


=== Known Issues

The Anypoint Monitoring log points feature is only supported on Anypoint runtime version 3.8.5 or later. For APIs not running on Anypoint runtime 3.8.5 or later, the log points feature does not appear for the API.

Since you can't select the runtime version when you deploy an API from API Manager, you need to navigate to Runtime Manager, select the runtime version (3.8.5 or later), then redeploy the API.

=== Fixed Issues

* General bug fixes.


== Version 1.05

=== New Features and Enhancements

* Environment-wide reporting on application performance, including requests, failures, CPU and memory utilization. (Requires a Titanium subscription)
* Performance Improvements
** All static resources are stored on a content delivery network (CDN).
** Resources are prefetched on page load.
** Changes to built-in dashboards load more quickly.
** Extended connection pools life before timeout.
* Improvements to Deployment and Management:
** New capabilities to associate an Organization with an environment so that you can build proofs of concept (POCs) without relying on engineering work.
** Provisioning Configuration Management: Allows for changes to the data sources without requiring a new deployment. Versioning to allow controlled roll out.
** Log Orchestration Service updates periodically from the Provisioning System: allows the creation of an Organization log index without requiring a deployment.
** Admin console now exposes data from Provisioning: it allows easier visualization and editing of the environment properties.
* Minor user experience (UX) improvements.
* Log search share URL.

=== Fixed Issues

* General bug fixes.
