= Anypoint Monitoring Installer Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]


These release notes are for patches made to the Anypoint Monitoring agent installer.

== Related Documentation

In addition to these release notes, see:

* xref:monitoring/anypoint-monitoring-release-notes.adoc[Anypoint Monitoring Release Notes]
* xref:monitoring::am-installing#update-the-monitoring-agent.adoc[Update the Monitoring Agent]
* xref:monitoring::index.adoc[Anypoint Monitoring]

[NOTE]
If you update the Runtime Manager agent, you must execute the Anypoint Monitoring agent uninstall script and then re-install the Anypoint Monitoring agent.

== Version 2.1.5.0 July 15, 2019

This release contains the following fixed issue:

Log forwarding does not work with Anypoint Monitoring agent 2.1.4.0 in hybrid runtime (SE-12410)

== Version 2.1.4.0 June 7, 2019

This release contains the following fixed issue:

High thread count in a clustered environment (SE-11772)

== Version 2.1.2.0 May 17, 2019

This release includes the following updates:


* Added support for Mule 4.2.x and Runtime Manager agent 2.3.x
* Added support for Filebeat restart if configuration or certificates have changed

This release includes the following fixed issues:

* Anypoint Monitoring with Multicast Cluster Setup (SE-11657)
* Layer when deploying app from RM (SE-10374)
* Fix NPE reported in Mule log at startup (SE-11483)
* Some inbound request failures are not taken into account in Monitoring dashboards (SE-10544)

== Version 2.1.0.0 March 26, 2019

This release includes support for the SOCKS5 proxy. For more information, see xref:monitoring::am-installing.adoc[Install the Anypoint Monitoring Agent].

You can download the Anypoint Monitoring agent installer from https://s3.amazonaws.com/cdn-anypoint-prod/artifacts/monitoring-center-ui/app/hybrid/am-2.1.0.0.zip[Anypoint Monitoring Agent Installer 2.1.0.0] or from the Anypoint Monitoring *Settings > Hybrid* page.

== Version 2.0.5.0 February 13, 2019

This release includes the following updates:

* Added metrics for operating system
* Added support for the following versions of Mule Runtime Manager agent:
** 1.11.x
** 1.12.x
** 2.2.x

You can download the Anypoint Monitoring agent installer from https://s3.amazonaws.com/cdn-anypoint-prod/artifacts/monitoring-center-ui/app/hybrid/am-2.0.5.0.zip[Anypoint Monitoring Agent Installer 2.0.5.0]

== Version 2.0.4.0 February 11, 2019

This release includes the following updates:

* Added support for Mule Runtime Manager agent version 2.1.8.
* Added support for Mule runtime engine version 4.1.5.
