= Anypoint Visualizer Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

This document describes new features and enhancements, known limitations, issues, and fixes for Anypoint Visualizer. See xref:visualizer::index.adoc[Anypoint Visualizer] documentation for more information.

== April 30, 2019

Visualizer now supports applications that are deployed to Runtime Fabric. See xref:visualizer::setup.adoc[Set up Anypoint Visualizer] for more information.

This release has the following known limitations:

* If a Mule 3 CloudHub application with the old Visualizer agent (version earlier than April 5, 2019) is calling a Runtime Fabric ingress endpoint, there will be extra edge from the CloudHub app to a node with the IP address for the controller. Please upgrade to the latest release of the Mule runtime engine.
* If a Mule 4 CloudHub application is calling a Runtime Fabric ingress endpoint, there will be and extra edge from the CloudHub app to a node with the IP address for the controller. You can use your filters within Visualizer to hide this node.
* If a Runtime Fabric Mule app is calling a Mule 3 CloudHub Mule app with the old Visualizer agent (version earlier than April 5, 2019) using its DNS, the correct connection will be drawn, but there will be an additional edge from the *External Traffic* node to the CloudHub application.
* If a Runtime Fabric Mule app is calling a Mule 4 CloudHub Mule app using its DNS, the correct connection will be drawn, but there will be an additional edge from the *External Traffic* node to the CloudHub application.
* If you have an application in two different clusters with the same name, these applications will appear as one node on the canvas. You should rename one application. 


== April 25, 2019

* Visualizer editors can define views so that everyone in the organization has a dynamic and consistent view of the architecture for each project. 
* All Visualizer users have a private view, which provides a complete picture of all the apps they have access to.

See xref:visualizer::view.adoc[Visualizer Views] for more information.

== April 5, 2019

* Anypoint Monitoring Agent Moving to Mule Version 3.9 Runtimes

** The latest patch release for Mule runtime engine version 3.9.x (04-05-2019 or later) includes an agent that unifies the Anypoint Monitoring and Anypoint Visualizer agents. Having this single agent means that applications using this Mule version display metrics in Visualizer and the -AM runtime version is no longer required.
** Upgrade to 4.1.x 03-22-2019 or later, or 3.9.x 04-05-2019 or later
+
. If you upgrade Mule 4 to the newest patch (03-22-2019 or later) or the Mule 3.9.x newest patch (04-05-2019 or later), you'll notice that you can't see your apps in Visualizer or Anypoint Monitoring. Don't worry, they are still running.
. You must xref:visualizer::setup.adoc[enable the Anypoint Monitoring agent] to see your applications appear in Visualizer after the upgrade.
+
[NOTE]
Please take careful note of which Mule versions that Visualizer now supports and xref:visualizer::setup.adoc[the necessary tasks to perform] (depending on the version) to ensure that your applications appear in Visualizer and have metrics enabled.

* Visualizer supports dedicated load balancers for apps using Mule version 3.9.x.
+
[NOTE]
While Visualizer doesn't yet support dedicated load balancers for apps using Mule version 4.1.x, MuleSoft anticipates that support for Mule version 4.2.
This anticipation is not a guarantee. Visualizer documentation and release notes will be updated when support is available.

== March 25, 2019

* Standalone Mule Only 
+
Due to a potential performance impact for Mule 4.1.x, header injection in the Anypoint Monitoring agent is now disabled by default for standalone Mule.
Visualizer does not work properly without this header, so to see your applications correctly, you must enable the property at the server level 
after you install the Anypoint Monitoring Agent. 
+
For instructions, see xref:visualizer::setup.adoc#_set_up_for_standalone_mule[Set up Anypoint Visualizer].

== March 23, 2019
Version 2.1.0

== New Features and Enhancements

* Side Panel
** Replaced Rename Node feature with the ability to modify the Display Name of a service from the Customization section of the details.

* View
** Layers set via application properties can no longer be overridden in the Customization section within the Visualizer UI.
** Layers can no longer be deleted or renamed. Instead, reassign a service to a new layer to accomplish the same outcome. 
*** All default layers (System, Process, Experience) will be offered by default and cannot be deleted.

* Anypoint Monitoring Agent Moving to Non-AM Runtimes

** The latest patch release for Mule runtime engine version 4.1.x (03-23-2019 or later) includes an agent that unifies the Anypoint Monitoring and Anypoint Visualizer agents. Having this single agent means that applications using this Mule version display metrics in Visualizer and the -AM runtime version is no longer required.
** Upgrade to 4.1.x 03-23-2019
+
. If you upgrade Mule 4 to the newest patch (03-23-2019 or later), you'll notice that you can't see your apps in Visualizer or Anypoint Monitoring. Don't worry, they are still running.
. You must xref:visualizer::setup.adoc[enable the Anypoint Monitoring agent] to see your applications appear in Visualizer after the upgrade.

[NOTE]
Please take careful note of which Mule versions that Visualizer now supports and xref:visualizer::setup.adoc[the necessary tasks to perform] (depending on the version) to ensure that your applications appear in Visualizer and have metrics enabled.


=== Changes to Layers

* Layer labels and names may change. The first letter of every layer will be capitalized. All default layers will be restored.

=== Changes to Display Name

add content

== February 11, 2019
Version 2.0.3

== New Features and Enhancements

* Side Panel
** Added *Export as PNG* button that allows users to export their network topology as it is currently displayed on the canvas.

== January 23, 2019
Version 2.0.2

== New Features and Enhancements

* View
** Edges shown between services are now active. This means that they appear only if there has been traffic in the past seven days. Non-active edges do not appear on the canvas. 
** When a service connects to a service in an organization in which a user does not have the *CloudHub Viewer* permission, the service the user does not have access to is displayed as an HTTP node. 


== January 8, 2019
Version 2.0.1 

== New Features and Enhancements

* Side Panel
** Changed *Include related services* box to a toggle named *Show dependents and dependencies*, which allows you to view dependencies of the nodes and services with the selected tags.
** Updated the placement of the *Select all/Select none* button for filtering. 
* View - Updated icon on node to indicate if application is deployed in CloudHub or on-premises. 

== Fixed Issues

* Hostname is no longer truncated in the details panel.
* Fixed *Select all/select none* button functionality to work as expected with search bar within environments and services filtering.


== December 15, 2018
Version 2.0.0

== New Features and Enhancements

* Added support for applications running in standalone Mule runtime engines. +
[NOTE]
This capability is being released incrementally.
* Added the ability to select multiple nodes on the Visualizer canvas so you can apply layers and tags to all selected nodes at once.

== Known Issues

* Standalone Mule runtime engines do not support HTTP calls using IP addresses instead of DNS names.
* When an application deployed to a standalone Mule runtime engine calls a CloudHub application, an extra edge is displayed. This issue is fixed in the `-AM` runtime only.

== November 27, 2018
Version: 1.7.0

=== New Features and Enhancements

* Side Panel
** Added the ability to add tags to services using the UI or properties
** Moved layer assignment from the *Details* panel to the *Customization* panel
** Added filtering by tags
** Added *Include related services* button to the *Services* filter


== November 13, 2018
Version: 1.6.0

=== New Features and Enhancements

* Side Panel
** Added filtering by environments and services (nodes)

=== Fixed Issues

* Dashboard button in side panel links to appropriate monitoring dashboard


== November 1, 2018
Version: 1.5.0

=== New Features and Enhancements

* View
** Added new text field to allow searching for nodes (services).
** Added dimming functionality for when service is selected. Clicked node and its dependencies will show and other services will be grayed out.


== October 3, 2018
Version: 1.3.1

=== New Features and Enhancements

* Side Panel
** Added links to Anypoint Monitoring dashboard and logs page (for premium users only) for selected nodes.
** Added a warning message to nodes that cannot be customized by user because of lack of permissions.


== September 28, 2018

Version: 1.3.0

=== New Features and Enhancements

* Side Panel
** Added API/Application monitoring metrics for selected node.
** Added embedded chart from Anypoint Monitoring for selected node.
* View
** In-line metrics displayed for the selected node.
** Drop-down to choose metric and time frame.
** Improved color themes.
* Permissions
** Removed the *Visualizer* viewer permission. Starting this release, Anypoint Visualizer uses the *CloudHub Application Read* permission to display which applications should be shown.

=== Fixed Issues

* Environments with legacy Id value are shown in the environment selector


== September 5, 2018
Version: 1.2.0

=== New Features and Enhancements

* Side Panel
** Removed "Highlight most depended-on nodes" checkbox.
* View
** Updated "Inbound connections" legend appearance.
** Updated color themes.


== August 21, 2018
Version: 1.1.0

=== New Features and Enhancements

* Improved node layout to minimize crossing arrows.
* Environment selector aligned to platform-level business group user experience.

=== Fixed Issues

* Allow special characters as node names
* Incorrect Node positioning in special circumstances

== July 27, 2018
Version: 1.0.2

=== New Features and Enhancements

* Changes to how permissions are managed
** Users can only see the environments in which they have Runtime Manager Read applications permission, or the administrator role.
** Users can only see the business groups that they have access to, and at least have one environment where they have view permissions.
* Layers
** Collapsed layers maintain the width of the canvas view


=== Fixed Issues

* Invalid dependency detected when using mule gateways
* When using a Mule 4 application the flow validation component was shown as a dependency.

=== Known Limitations and Workarounds

There are no known limitations or workarounds in this release.


== June 30, 2018
Version: 1.0.0

=== New Features and Enhancements

This is the initial release of Anypoint Visualizer. Anypoint Visualizer provides a graphical representation of the APIs, and Mule applications, and third-party systems within your application network.

See xref:visualizer::index.adoc[Anypoint Visualizer] for more information.

=== Changes in This Release

This release contains no feature changes.

=== Fixed Issues

There are no fixed issues in this release.

=== Known Limitations and Workarounds

There are no known limitations or workarounds in this release.

=== Upgrade Requirements

To use Anypoint Visualizer, you must deploy you application to a supported version of Mule Runtime on CloudHub.

=== Compatibility Notes

Anypoint Visualizer supports the following Mule runtimes running on CloudHub:

* Mule Runtime, version 3.9.x
* Mule Runtime, version 4.1.2

**Note**: Applications using supported runtimes before June 30th, will have to update the runtime, which can be done with 0-downtime for CloudHub applications, APIs and proxies.
