= Anypoint Visualizer Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

This document describes new features and enhancements, known limitations, issues, and fixes for Anypoint Visualizer. See xref:visualizer::index.adoc[Anypoint Visualizer] for more information.

== October 2, 2018
Version: 1.3.1

=== New Features and Enhancements

* Side Panel
** Added links to Anypoint Monitoring dashboard and logs page (for premium users only) for selected nodes.
** Added message to nodes that cannot be customized by user because of lack of CloudHub Administrator permissions.


== September 28, 2018
Version: 1.3.0

=== New Features and Enhancements

* Side Panel
** Added API/Application monitoring metrics for selected node.
** Added embedded chart from Anypoint Monitoring for selected node.
* View
** In-line metrics displayed for the selected node.
** Drop-down to choose metric and time frame.
** Improved color themes.
* Permissions
** Removed the *Visualizer* viewer permission. Starting this release, Anypoint Visualizer uses the *CloudHub Application Read* permission to display which applications should be shown.

=== Fixed Issues

* Environments with legacy Id value are shown in the environment selector


== August 21, 2018
Version: 1.1.0

=== New Features and Enhancements

* Improved node layout to minimize crossing arrows.
* Environment selector aligned to platform-level business group user experience.

=== Fixed Issues

* Allow special characters as node names
* Incorrect Node positioning in special circumstances

== July 27, 2018
Version: 1.0.2

=== New Features and Enhancements

* Changes to how permissions are managed
** Users can only see the environments in which they have Runtime Manager Read applications permission, or the administrator role.
** Users can only see the business groups that they have access to, and at least have one environment where they have view permissions.
* Layers
** Collapsed layers maintain the width of the canvas view


=== Fixed Issues

* Invalid dependency detected when using mule gateways
* When using a Mule 4 application the flow validation component was shown as a dependency.

=== Known Limitations and Workarounds

There are no known limitations or workarounds in this release.


== June 30, 2018
Version: 1.0.0
=== New Features and Enhancements

This is the initial release of Anypoint Visualizer. Anypoint Visualizer provides a graphical representation of the APIs, and Mule applications, and third-party systems within your application network.

See xref:visualizer::index.adoc[Anypoint Visualizer] for more information.

=== Changes in This Release

This release contains no feature changes.

=== Fixed Issues

There are no fixed issues in this release.

=== Known Limitations and Workarounds

There are no known limitations or workarounds in this release.

=== Upgrade Requirements

To use Anypoint Visualizer, you must deploy you application to a supported version of Mule Runtime on CloudHub.

=== Compatibility Notes

Anypoint Visualizer supports the following Mule runtimes running on CloudHub:

* Mule Runtime, version 3.9.x
* Mule Runtime, version 4.1.2

**Note**: Applications using supported runtimes before June 30th, will have to update the runtime, which can be done with 0-downtime for CloudHub applications, APIs and proxies.
