= Runtime Manager Agent 2.2.0 Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

_January 28, 2018_

This document describes new features and enhancements, known limitations, issues, and fixes in Anypoint Runtime Manager Agent, version 2.2.0.

== New Features and Enhancements

This release contains the following new features or enhancements:

* Added Java 11 OpenJDK Support

== Changes in This Release

* Changed to connect to the new Runtime Manager Publicly certified endpoints for Mule Manager and Auth Proxy
* Now the Mule Agent API returns bad request (400) instead of internal server error (500) when enabling a service with null log configuration

== Fixed Issues

This release contains the following issue fixes:

* Issue that caused a NPE when processing ExceptionNotification from implicit error handler

== Known Limitations and Workarounds

There are no known limitations or workarounds in this release.

== Upgrade Requirements

* Upgrade procedure will result in the use of 2 new endpoints for communicating with Anypoint Runtime Manager. Before doing any upgrade, please ensure there is no networking constraint accessing the following FQDNs on port 443:
    * ws://runtime-manager.anypoint.mulesoft.com, ws://runtime-manager.eu1.anypoint.mulesoft.com
    * https://data-authenticator.anypoint.mulesoft.com, https://data-authenticator.eu1.anypoint.mulesoft.com

== Compatibility Notes

[%header%autowidth.spread,cols="a,a"]
|===
|Software|Version
|Mule Runtime| This agent version is compatible only with Mule 4.1.x versions.
|JDK      |JRE 1.8.0 (Recommended JRE 1.8.0_151/52)
|OS       |MacOS 10.11.x, HP-UX 11i V3, AIX 7.2, Windows 2016 Server, Windows 10, Solaris 11.3, RHEL 7, Ubuntu Server 16.04
|Runtime Manager|V2.10.0+
|===
