= Runtime Manager Agent 1.11.1 Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

_October 10, 2018_

This document describes new features and enhancements, known limitations, issues, and fixes in Anypoint Runtime Manager Agent, version 1.11.1

== New Features and Enhancements

This release contains no new features or enhancements.

== Changes in This Release

This release contains no changes to existing functionality.

== Fixed Issues

This release contains the following issue fixes:

* Disabling Insights removes remove the YAML configuration section.
* Upgraded the versions of several dependency libraries.

== Known Limitations and Workarounds

There are no known limitations or workarounds in this release.

== Upgrade Requirements

There are no upgrade requirements for this release.

== Compatibility Notes

[%header%autowidth.spread,cols="a,a"]
|===
|Software|Version
|Mule Runtime|3.6.x, 3.7.x, 3.8.x, 3.9.x
|API Gateway|2.x and above
|JDK    |JRE 1.7.0 (Recommended JRE 1.7.0_79/80)
|Runtime Manager|V2.0
|===
