= Runtime Manager Agent 2.1.9 Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

_December 7, 2018_

This document describes new features and enhancements, known limitations, issues, and fixes in Anypoint Runtime Manager Agent, version 2.1.8.

== New Features and Enhancements

This release contains the following features or enhancements:

* Support for batching mule events when using disk buffer.

== Changes in This Release

This release contains no changes to existing functionality.

== Fixed Issues

This release contains the following issue fixes:

* No longer losing events when using disk buffer due to the limit size on the in-memory buffer it uses.
* Upgraded the versions of several dependency libraries.

== Known Limitations and Workarounds

There are no known limitations or workarounds in this release.

== Upgrade Requirements

There are no upgrade requirements for this release.

== Compatibility Notes

[%header%autowidth.spread,cols="a,a"]
|===
|Software|Version
|JDK     |JDK 1.8.0 (Recommended JDK 1.8.0_151/52)
|OS      |MacOS 10.11.x, HP-UX 11i V3, AIX 7.2, Windows 2016 Server, Windows 10, Solaris 11.3, RHEL 7, Ubuntu Server 16.04
|===
