= Runtime Manager Agent 2.2.0 Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

_January 28, 2018_

This document describes new features and enhancements, known limitations, issues, and fixes in Anypoint Runtime Manager Agent, version 2.2.0.

== New Features and Enhancements

This release contains the following new features or enhancements:

* Added Java 11 OpenJDK Support

== Changes in This Release

* This version of Runtime Manager Agent enables connection to the new Runtime Manager Publicly Certified endpoints for Mule Manager and Auth Proxy.
* Now, when enabling a service that has a null log configuration, the Mule Agent API returns a bad request (400) instead of an internal server error (500).

== Fixed Issues

This release contains the following fixed issue:

* The issue that caused an NPE when processing `ExceptionNotification` from the implicit error handler is fixed. 

== Known Limitations and Workarounds

There are no known limitations or workarounds in this release.

== Upgrade Requirements

When you upgrade the agent two new endpoints for communicating with Anypoint Runtime Manager are created. 

[NOTE]
Before performing the upgrade, ensure there are no networking constraints for accessing the FQDNs on port 443.

. In the `mule-agent.yml` file, configure the following URLs in the appropriate section.
+
[cols="1,1", options="header"]
|===
|United States |EU
a|
`ws://runtime-manager.anypoint.mulesoft.com`

`+https://data-authenticator.anypoint.mulesoft.com+`
a|
`ws://runtime-manager.eu1.anypoint.mulesoft.com`

`+https://data-authenticator.eu1.anypoint.mulesoft.com+`
|===
+
For the `ws` protocol, change the `websocket.transport` URI to `ws://runtime-manager.anypoint.mulesoft.com` like in the following example:
+
----
 websocket.transport:
    enabled: true
    consoleUri: ws://runtime-manager.anypoint.mulesoft.com
----
+
For the HTTPS protocol, change
`+https://arm-auth-proxy.prod.cloudhub.io+` to
`+https://data-authenticator.anypoint.mulesoft.com+` like in the following example:
+
----
authenticationProxy:
    endpoint: https://data-authenticator.anypoint.mulesoft.com
----
+
. Restart the Mule runtime engine.

== Compatibility Notes

[%header%autowidth.spread,cols="a,a"]
|===
|Software|Version
|Mule Runtime| This agent version is compatible only with Mule 4.1.x versions.
|JDK      |JRE 1.8.0 (Recommended JRE 1.8.0_151/52)
|OS       |MacOS 10.11.x, HP-UX 11i V3, AIX 7.2, Windows 2016 Server, Windows 10, Solaris 11.3, RHEL 7, Ubuntu Server 16.04
|Runtime Manager|V2.10.0+
|===
