= Runtime Manager Agent 1.12.0 Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

_January 28, 2018_

This document describes new features and enhancements, known limitations, issues, and fixes in Anypoint Runtime Manager Agent, version 1.12.0.

== New Features and Enhancements

This release contains no new features or enhancements.

== Changes in This Release

* This version of Runtime Manager Agent uses a new Publicly Certified certificate and connects to two new endpoints in Anypoint Runtime Manager.
* Now, when enabling a service that has a null log configuration, the Mule Agent API returns a bad request (400) instead of an internal server error (500).

== Fixed Issues

This release contains no fixed issues.

== Known Limitations and Workarounds

There are no known limitations or workarounds in this release.

== Upgrade Requirements

The agent upgrade procedure results in the use of two new endpoints for communicating with Anypoint Runtime Manager. Before doing any upgrade, ensure there are no networking constraints for accessing the FQDNs on port 443.

For runtimes connecting to Anypoint Runtime Manager in the US:

* ws://runtime-manager.anypoint.mulesoft.com
* https://data-authenticator.anypoint.mulesoft.com

For runtimes connecting to Anypoint Runtime Manager in the EU:

* ws://runtime-manager.eu1.anypoint.mulesoft.com
* https://data-authenticator.eu1.anypoint.mulesoft.com

== Compatibility Notes

[%header%autowidth.spread,cols="a,a"]
|===
|Software|Version
|Mule Runtime|3.6.x, 3.7.x, 3.8.x, 3.9.x
|API Gateway|2.x and above
|JDK    |JRE 1.7.0 (Recommended JRE 1.7.0_79/80)
|OS       |MacOS 10.11.x, HP-UX 11i V3, AIX 7.2, Windows 2016 Server, Windows 10, Solaris 11.3, RHEL 7, Ubuntu Server 16.04
|Runtime Manager|V2.10.0+
|===
