= Runtime Manager Agent 1.11.3 Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

_December 7, 2018_

This document describes new features and enhancements, known limitations, issues, and fixes in Anypoint Runtime Manager Agent, version 1.11.3.

== New Features and Enhancements

This release contains the following new features or enhancements:

* Added support for flushing disk-buffered Mule events in batches of a configurable size.

== Changes in This Release

This release contains no changes to existing functionality.

== Fixed Issues

This release contains the following issue fixes:

* Issue that caused buffered events to be discarded when using disk buffer in the scenario that buffered events exceeded in-memory limit size.
* Upgraded the versions of several dependency libraries.

== Known Limitations and Workarounds

There are no known limitations or workarounds in this release.

== Upgrade Requirements

There are no upgrade requirements for this release.

== Compatibility Notes

[%header%autowidth.spread,cols="a,a"]
|===
|Software|Version
|Mule Runtime|3.6.x, 3.7.x, 3.8.x, 3.9.x
|API Gateway|2.x and above
|Java    |JRE 1.7.0, 1.8.0 [Oracle, IBM, OpenJDK]
|Runtime Manager|V2.0
|===
