= Runtime Manager Agent 2.2.1 Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

_February 19, 2019_

This document describes new features and enhancements, known limitations, issues, and fixes in Anypoint Runtime Manager Agent, version 2.2.1.

== New Features and Enhancements

This release contains no new features or enhancements.

== Changes in this Release

* The API will now return the Root Cause when an application fails to deploy. 
* Application Properties will only be stored in the Application yml descriptor, no longer in the mule-agent.yml .
* For APCE environments, trusted certificates will always be used from JKS file instead of JVM.

== Fixed Issues

This release contains the following fixed issues:

* Application fails at Restart from side panel due to property not found.
* TransactionNotification related errors are filled in the application log when tracking is enabled in 4.1.x, instead of the mule_ee.log .
* Support for 'host' property in Cloudhub properties cause application fails to deploy.

= Known Limitations and Workarounds

There are no known limitations or workarounds in this release.

== Upgrade Requirements

There are no upgrade requirements for this release.

== Compatibility Notes

[%header%autowidth.spread,cols="a,a"]
|===
|Software|Version
|Mule Runtime| This agent version is compatible only with Mule 4.1.x versions.
|JDK      |JRE 1.8.0 (Recommended JRE 1.8.0_151/52)
|OS       |MacOS 10.11.x, HP-UX 11i V3, AIX 7.2, Windows 2016 Server, Windows 10, Solaris 11.3, RHEL 7, Ubuntu Server 16.04
|Runtime Manager|V2.10.0+
|===
