= Runtime Manager Agent 1.14.0 Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Jul 15, 2019

This document describes new features and enhancements, known limitations, issues, and fixes in Anypoint Runtime Manager agent, version 1.14.0.

== New Features and Enhancements

This release contains the following new features or enhancements:

* Atomic schedulers modifications: A new HTTP endpoint in the Mule Runtime Manager agent API will modify schedulers' settings atomically so that other schedulers deployed to the same Mule runtime engine are not triggered. Prior to this update, modifications to schedulers forced the synchronous trigger of the schedulers of all applications running in the same Mule runtime engine.

== Changes in This Release

This release contains no changes to existing functionality.

== Fixed Issues

This release contains no fixed issues.

== Known Limitations and Workarounds

There are no known limitations or workarounds in this release.

== Upgrade Requirements

There are no upgrade requirements for this release.

== Compatibility Notes

[%header%autowidth.spread,cols="a,a"]
|===
|Software|Version
|Mule Runtime|3.6.x, 3.7.x, 3.8.x, 3.9.x
|API Gateway|2.x and above
|Java    |JRE 1.7.0, 1.8.0 [Oracle, IBM, OpenJDK]
|OS       |MacOS 10.11.x, HP-UX 11i V3, AIX 7.2, Windows 2016 Server, Windows 10, Solaris 11.3, RHEL 7, Ubuntu Server 16.04
|Runtime Manager|V2.12.0+  
|===
