= Runtime Manager Agent 1.12.1 Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

_February 19, 2019_

This document describes new features and enhancements, known limitations, issues, and fixes in Anypoint Runtime Manager Agent, version 1.12.1.

== New Features and Enhancements

This release contains the following new features or enhancements:

* For Cloudhub: The agent now returns the root cause error when an application failures to deploy.

== Changes in This Release

* The application properties will only be save into the application descriptor instead of the Mule Agent's descriptor.

== Fixed Issues

This release contains the following fixed issues:

* Fix install/upghrade errors in the PCE environment.
* Solves application failures when using a property named 'host'.

== Known Limitations and Workarounds

There are no known limitations or workarounds in this release.

== Upgrade Requirements

There are no upgrade requirements for this release.

== Compatibility Notes

[%header%autowidth.spread,cols="a,a"]
|===
|Software|Version
|Mule Runtime|3.6.x, 3.7.x, 3.8.x, 3.9.x
|API Gateway|2.x and above
|JDK    |JRE 1.7.0 (Recommended JRE 1.7.0_79/80)
|OS       |MacOS 10.11.x, HP-UX 11i V3, AIX 7.2, Windows 2016 Server, Windows 10, Solaris 11.3, RHEL 7, Ubuntu Server 16.04
|Runtime Manager|V2.10.0+
|===
