= Runtime Manager Agent 2.1.7 Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

_October 08, 2018_

This document describes new features and enhancements, known limitations, issues, and fixes in Anypoint Runtime Manager Agent, version 2.1.7.

== New Features and Enhancements

This release contains no new features or enhancements.

== Changes in This Release

This release contains no changes to existing functionality.

== Fixed Issues

This release contains the following issue fixes:

* For Studio : DataWeaver preview now always set payload, vars and attribute variables .

== Known Limitations and Workarounds

There are no known limitations or workarounds in this release.

== Upgrade Requirements

There are no upgrade requirements for this release.

== Compatibility Notes

[%header%autowidth.spread,cols="a,a"]
|===
|Software|Version
|JDK    |JDK 1.8.0 (Recommended JDK 1.8.0_151/52)
|OS      |MacOS 10.11.x, HP-UX 11i V3, AIX 7.2, Windows 2016 Server, Windows 10, Solaris 11.3, RHEL 7, Ubuntu Server 16.04
|Mule 4.1.x | This agent version is compatible only with Mule 4.1.x versions.
=======
|===
