= Runtime Manager Agent 1.12.1 Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

_February 19, 2019_

This document describes new features and enhancements, known limitations, issues, and fixes in Anypoint Runtime Manager Agent, version 1.12.1.

== New Features and Enhancements

This release contains no new features or enhancements.

== Changes in This Release

* The API now returns the root cause when an application fails to deploy. 
* Application properties are now stored in the application `yml` descriptor instead of in the `mule-agent.yml`.
* For APCE environments, trusted certificates are always used from the JKS file instead of the JVM.

== Fixed Issues

This release contains the following fixed issues:

* Support for the `host` property in CloudHub properties caused applications to fail to deploy.

== Known Limitations and Workarounds

There are no known limitations or workarounds in this release.

== Upgrade Requirements

There are no upgrade requirements for this release.

== Compatibility Notes

[%header%autowidth.spread,cols="a,a"]
|===
|Software|Version
|Mule Runtime|3.6.x, 3.7.x, 3.8.x, 3.9.x
|API Gateway|2.x and above
|JDK    |JRE 1.7.0 (Recommended JRE 1.7.0_79/80)
|OS       |MacOS 10.11.x, HP-UX 11i V3, AIX 7.2, Windows 2016 Server, Windows 10, Solaris 11.3, RHEL 7, Ubuntu Server 16.04
|Runtime Manager|V2.10.0+
|===
