= Anypoint Runtime Manager Version 2.9.0 Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

_Dec 8, 2018_

This document describes new features and enhancements, known limitations, issues, and fixes in Anypoint Runtime Manager version 2.9.0.

== New Features and Enhancements

This release contains the following new feature:

* *Application Versioning*: This feature enables Runtime Fabric users to view the application deployment history, as well as a history of all changes made to deployed configurations. It also gives users an in-depth view of the cluster replica statuses. This feature is available only in the Runtime Manager UI and API for this release.

See xref:1.0@runtime-fabric::app-versioning.adoc[Application Deployment Versioning] for more information.

== Changes in This Release

This release contains no feature changes.

== Fixed Issues

* The issue where properties supplied through the UI were not propagated during restart of the application is fixed.

== Known Limitations and Workarounds

There are no known limitations or workarounds in this release.

== Upgrade Requirements

There are no upgrade requirements for this release.

== Compatibility Notes

* Application versioning is compatible with all Runtime Fabric versions.
