= Design Center Release Notes: Features for Creating API Specifications
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

These release notes cover the following versions of these features:

* <<2-4-0,2.4.0>>
* <<2-2-9,2.2.9>>
* <<2-2-8,2.2.8>>
* <<2-2-7,2.2.7>>
* <<2-2-6,2.2.6>>
* <<2-2-5,2.2.5>>

== 2.4.0
*January 12, 2019*

This release contains an enhancement and fixes a number of issues.

=== Enhancement

The API editor is now using the AMF parser. This parser checks for full conformance with the RAML specification (either 0.8 or 1.0) that is being used for an API specification. If you reopen in the API editor any RAML API specifications that have already been published, you might find that there are instances of invalid RAML that the previous parser did not flag. For more information about what to do in such cases, see xref:design-center::design-modify-raml-specs-conform.adoc[Modify Published RAML API Specifications to Conform Completely to RAML 0.8 or 1.0].

The AMF parser is at version 2.0.0.

=== Fixed Issues

// SE-



// SE-7433
* A problem occurred in which an API specification could not be tested with the mocking service when OAuth 2.0 was used for security. Clicking *Authorize and Send* after filling in all of the required authentication information merely resulted in the message "Fill in the authorization form first".
// SE-7817
* The API editor did not detect that an incorrect JSON schema was being referenced.
// SE-7869
* The API console pane of the API editor was sometimes not being refreshed as different types were being selected. The same problem could occur as different responses were selected.
* There were a few formatting problems in the information displayed in the API console pane.
// SE-7898
* Swedish characters were not supported in the Crowd release (November 2017).
// SE-8242
* If a RAML API specification contained a DataType that extended another DataType, the information shown in the API console pane about the extending DataType could sometimes be incorrect.
// SE-8323
* The API editor could take too long to resolve one or more DataType resources. During that time, the API console pane was blank.
// SE-8424
* When a RAML extension extended a file that used a library that was itself defined in a fragment, and the library included a trait with the `!include` tag, the API editor was unable to locate the trait.
// SE-8464
* If a RAML API fragment defined multiple properties as `<propertyName>: string | nil`, the API console pane did not display any information, or did so only after a long delay, after the API specification that referenced the fragment was opened.
// SE-8628, SE-9703
* If a project included a JSON schema, and that file itself included another JSON schema, Design Center failed to load the second schema.
// SE-9121
* The API editor was requiring the media type to be declared for message bodies, even though the RAML specifications state that `mediaType` is optional for `body` nodes.
// SE-9165
* If you tried to import a Swagger 2.0 JSON file that contained an array of objects, Design Center threw a parsing error.
// SE-9269
* The mocking service was not presenting a choice of authentication methods when a basic `securityScheme` was being referenced from a library RAML fragment.
// SE-9276
* It was possible for projects imported into Anypoint Studio from the API editor in Design Studio to contain RAML errors that were not pointed out by the API editor.
// SE-9493
// I've asked a question in the ticket.
// SE-9545
* RAML errors not reported by the API editor could cause problems in the API console pane, such as failures to display various pieces of information.
// SE-9284
* If a `uses` node specified an invalid path to a library, the API editor displayed this unhelpful message:
+
----
Cannot read property 'ast' of null at (1, 0)
----
+
The message has been improved.
// SE-9994
* The API editor was allowing a blank line as the first line in RAML files.
// SE-10064
* For very large API specifications, validation and the appearance of the API Console in the API editor could require much more time than usual.
// SE-10137
* If an endpoint were simply `/`, the API editor would throw a parsing error.
// SE-10144
* In the API console of the API editor, query parameters did not appear after you clicked the *Try It* button.
// SE-10150
* Changing the version number of an API specification that you were publishing to Exchange would change the value of all instances of the "version" keyword in the specification. Only the value for the root instance should have been changed.


== 2.2.9
*August 9, 2018*

This release contains an enhancement.

=== Enhancement

If your organization contains more than one business group, you can now select the group ID to associate an API specification with when you publish that specification to Anypoint Exchange.

== 2.2.8

*July 26, 2018*

This release introduces a change and fixes for several issues.

=== Enhancement

The code editor now supports the following structure for the declaration of a `baseUri` in specifications that are written in RAML 1.0:

[source,raml,linenums]
----
baseUri:
  value: http://www.example.com/api
----

=== Fixed Issues

* OAS files with identical names were allowed to be imported. There was no check to find out whether existing OAS 2.0 files in a project already had the same name as an OAS 2.0 file being imported.
* The `protocols` node was not being validated either in the code editor or in the visual editor.
* Error messages were not appearing for invalid `examples` nodes. Here is an example of an invalid `examples` node:

[source,raml,linenums]
----
title: New API

types:
  ids:
    type: object
    properties:
      identification:
        type: string
        examples:
          - MuleSoft
          - Salesforce
----

The correct way to define this `examples` node would be as follows:

[source,raml,linenums]
----
title: New API

types:
  ids:
    type: object
    properties:
      identification:
        type: string
        examples:
          id1: MuleSoft
          id2: Salesforce
----

The symbol `-`, which is used incorrectly in the invalid `examples` node is used for defining elements in arrays, as in this example:

[source,raml,linenums]
----
title: New API

types:
  ids:
    type: object
    properties:
      identification:
        type: array
        examples:
          id1:
            - MuleSoft
            - Salesforce
          id2:
            - Mule
            - CRM
----

* Uploading an API-specification project by using `anypoint-cli` resulted in the following message if the project contained a large number of files:
+
`Error: Could not open JPA EntityManager for transaction; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.JDBCConnectionException: Could not open connection`
* Importing an OAS 2.0 file that used parentheses in its name resulted in an error, but the error message did not explain the problem well.
* The conversion of an OAS 2.0 file to RAML, which takes place when an OAS file is imported, resulted in the `required` field in the properties of response objects being set to `false` even when the value in the OAS file was `true`.
* Attempts to import either RAML files or OAS 2.0 files via URL failed. If you tried to import a RAML file via URL, the file appeared empty in the code editor. If you tried to import an OAS 2.0 file via URL, the *Import* dialog would display the error message `Invalid OAS document`.
* When switched on, the mocking service could incorrectly insert the URI to the mocking server.
* It was possible to import an example into an API-specification project that was in read-only mode.
* If in the code editor you clicked the plus sign in the left sidebar, selected *Other* in the *Add New File* dialog, and then clicked *Create* without specifying a name for the file, a new file with the name `*/` appeared in the file list. It was not possible to delete that file.


== 2.2.7

*May 16, 2018*

This release fixes these issues:

* Supplying a base URI parameter in the visual editor, using the parameter in a base URI, closing the visual editor, and then reopening the project resulted in an error message and a blank middle panel.
* Selecting the type Number for a new Data Type in the visual editor, specifying a format, and changing the type to Integer resulted in the RAML viewer still including the specified number format.
* In the visual editor, changing the type for a base URI parameter caused the RAML viewer to show the new type, but the *Type* field continued to show the previously selected type.


== 2.2.6

*April 20, 2018*

This release fixes these issues:

* Attempts to import OAS JSON files would result in this error message being displayed: `Cannot read property 'hasOwnProperty' of null`  Such files could also fail to be converted by the JSON-to-RAML online conversion tool.
* Some warning and error messages were not being displayed.


== 2.2.5

*April 6, 2018*

This release includes two enhancements and fixes an issue.

=== Enhancements

* The left sidebar of the editor now lists groups, their resources, and their datatypes.
* An example API to use in the visual editor is now available from a link in the left sidebar.

=== Fixed Issue

The word "type" could not be used as the name of a property in a RAML API specification.
