= Release Notes for API Designer
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

These release notes cover the following versions of these features:

* <<2-4-6,2.4.6>>
* <<2-4-5,2.4.5>>
* <<2-4-4,2.4.4>>
* <<2-4-3,2.4.3>>
* <<2-4-2,2.4.2>>
* <<2-4-1,2.4.1>>
* <<2-4-0,2.4.0>>
* <<2-2-9,2.2.9>>
* <<2-2-8,2.2.8>>
* <<2-2-7,2.2.7>>
* <<2-2-6,2.2.6>>
* <<2-2-5,2.2.5>>

== 2.4.6
*April 20, 2019*


=== Fixed Issues
// SE-10861
* Specifications that were several MB in size could not be published to Exchange.
// SE-10917
* Resource types and traits in API specifications that were written in RAML 1.0 were not being validated.
// SE-11123
* A project might never finish loading if you created the project in the visual API editor, created a data type in that project, closed the project, and then attempted to reopen the project.
// SE-11193
* The API editor returned the error message `Recursive type at (_x_, _y_)` for recursive DataType definitions.
// SE-11374
* The mocking service would fail if an API specification used the `example` facet, rather than the `examples` facet, to include a NamedExample fragment.

== 2.4.5
*April 6, 2019*

This release includes a new feature, two enhancements, and two fixes.

=== New Feature

// DESIGNER-3463
The editor now caches validations that are made by the AMF parser. (This parser was released on January 10 this year in the 2.4.0 release. See the release notes for 2.4.0 for more details about it.) Every time a file was opened in previous releases, the AMF parser would validate the file; during the validation, the API console would not appear in the right-hand pane of the editor. Now, opening a file does not cause the AMF parser to validate it. Therefore, the API console appears immediately whenever you switch to another file in a project. Any change to a project -- typing, importing a file, or other actions -- clears the project's cache and triggers the AMF parser to validate the project again.

=== Enhancements

* The usability of the feature for forking projects is improved.
* The navigation bar at the top of API Designer is now consistent with the navigation bars in other tools within Design Center.

// I'm not documenting the color change in the sidebar. It is a very minor change.

=== Fixed Issues

//SE-11361
* The option *API is behind a firewall*, which you can toggle on and off by clicking the shield that is on the left side of the toggle for the mocking service, was not functional.
// SE-11353
* The validation of headers was not occurring when the headers were defined in RAML files that were included as dependencies from Anypoint Exchange.
// SE-11505
* API Designer did not release a user's lock on a project branch if the user left the project in the API editor by clicking the hamburger icon (the stack of three horizontal bars) in the top-left corner of the screen. Subsequently, no other user could edit the project branch until the previous user opened the project, opened the branch, and then left the project by clicking *Design Center* to the right of the hamburger icon.

// I documented none of the other fixed issues because they were not reported by customers.

== 2.4.4
*March 23, 2019*

This release fixes six issues.

=== Fixed Issues
// SE-11152
* When you are working on an API fragment, the editor now no longer displays the switch to turn on the mocking service.
// SE-11095
* When the documentation displayed in the *Documentation* pane contains more lines than the pane can accommodate, the pane does not display a scrollbar. Therefore, it is not possible to see all of the documentation.
// SE-10926
* Properties that are defined as numbers in the body of an API appear as strings in the API console.
// SE-10879
* The mocking service might return a response in JSON, even though the specification defined responses to be in XML.
// SE-9582
* The mocking service responded with a `400 Bad Request` error if a RAML API specification defined a JSON type for an HTTP header.
// SE-10974
* The editor did not display an error message when a NamedExample fragment contained properties that the RAML specification does not allow.

== 2.4.3
*February 23, 2019*

This release fixes two issues.

=== Fixed Issues
// SE-10793
* The behavior of the *Import API Example* dialog was faulty, making a selection difficult. You can open this dialog when you first create an API-specification project by clicking the word "example" in the sentence "Start project from an existing example," which appears in the left pane of the editor
// SE-10890
* The mocking service created invalid OAuth redirect URLs.


== 2.4.2
*February 9, 2019*

This release fixes a number of issues.

=== Fixed Issues
// SE-10631
* When the Mocking Service was on, the right pane of the editor was not displaying examples of JSON types for request bodies.
// SE-10632
* The editor did not show errors when the facet `properties` was declared twice for a type.
// SE-10659
* The editor displayed the error message `Expecting !!str and !!int provided` when numbers were used as keys in type definitions and in named examples.
// SE-10701
* For type declarations such as the one in this example, the editor displayed an error message that said the example value should be a multiple of the value of the `multipleOf` key:
----
#%RAML 1.0 DataType
displayName: exampleType
type: number
multipleOf: 0.01
example: 19.99
----
// SE-10702
* The editor displayed the following error message after parsing a RAML project that included an XSD schema: `The schema document '<filename>.xsd' cannot include itself`
// SE-10779
* MIME types are now validated as strings, not as regular expressions.
// SE-10863
* Auto-completion after elements such as `uses` and `!include` was not working, and suggestions for content to place after such elements were not being offered.

== 2.4.1
*January 25, 2019*

This release includes enhancements and fixes a number of issues.

=== Enhancements

* *For projects created before January 10, 2019:* You can turn on or off the stricter validation that began with the 2.4.0 release on January 10, 2019. You might want to do so to work with in an API-specification project that was created before this date, but don't yet have plans for resolving the messages that this validation displays.
+
To turn this validation off, toggle the switch that is labeled *Show Strict Errors* in the top-right corner of the editor. The default is On.
+ Even if you toggle this validation off, the grace period in which you must resolve the messages is still in effect. The grace period lasts at least until January 10, 2020.
* The documentation describes additional RAML problems that generate violation and warning messages since the 2.4.0 release.


=== Fixed Issues

// SE-10558
* When a RAML specification uses an `example` facet was being used, rather than an `examples` facet, the API editor displays a message. In the previous release, the message was not clear.
// SE-10631
* Design Center was not using the latest version of the API Console. Therefore, the JSON type for request bodies was not appearing in the right-hand pane of the API editor.
// SE-10639
* In Firefox, the body of POST and PUT requests was not appearing when the mocking service was being used, preventing requests from being sent correctly.


== 2.4.0
*January 10, 2019*

This release includes several enhancements and fixes a number of issues.

=== Enhancement

* The API editor (one of the two editors in Design Center's API Designer) is now using the AMF parser. This parser checks for full conformance with the RAML specification (either 0.8 or 1.0) that is being used for an API specification. If you reopen in the API editor any RAML API specifications that have already been published, you might find that there are instances of stricter validation. For more information about what to do in such cases, see xref:design-center::design-modify-raml-specs-conform.adoc[Modify Published RAML API Specifications to Conform Completely to RAML 0.8 or 1.0].
+
The AMF parser is at version 2.0.0.
* The Design Center now provides native support for OAS 2.0. To learn more, xref:design-center::design-create-publish-api-specs.adoc[see the documentation].
* The names of projects for API specifications and API fragments can now be as long as 64 characters.
* The option to download a project in YAML is now replaced with the following options, which you can access by clicking the three dots next to the name of a specification in the left pane:
** *Download as*: Downloads a RAML specification as an OAS specification, or an OAS specification as a RAML specification.
+
[WARNING]
====
The downloaded file is not guaranteed to be a correct specification.
====
** *Convert*: Converts a RAML specification to an OAS specification, or an OAS specification to a RAML specification.
+
[WARNING]
====
The converted file is not guaranteed to be a correct specification.
====

=== Fixed Issues

// SE-7433
* A problem occurred in which an API specification could not be tested with the mocking service when OAuth 2.0 was used for security. Clicking *Authorize and Send* after filling in all of the required authentication information merely resulted in the message "Fill in the authorization form first".
// SE-7817
* The API editor did not detect that an incorrect JSON schema was being referenced.
// SE-7869
* The API console pane of the API editor was sometimes not being refreshed as different types were being selected. The same problem could occur as different responses were selected.
* There were a few formatting problems in the information displayed in the API console pane.
// SE-7898
* Swedish characters were not supported in the Crowd release (November 2017).
// SE-8242
* If a RAML API specification contained a DataType that extended another DataType, the information shown in the API console pane about the extending DataType could sometimes be incorrect.
// SE-8323
* The API editor could take too long to resolve one or more DataType resources. During that time, the API console pane was blank.
// SE-8424
* When a RAML extension extended a file that used a library that was itself defined in a fragment, and the library included a trait with the `!include` tag, the API editor was unable to locate the trait.
// SE-8464
* If a RAML API fragment defined multiple properties as `<propertyName>: string | nil`, the API console pane did not display any information, or did so only after a long delay, after the API specification that referenced the fragment was opened.
// SE-8628, SE-9703
* If a project included a JSON schema, and that file itself included another JSON schema, Design Center failed to load the second schema.
// SE-9121
* The API editor was requiring the media type to be declared for message bodies, even though the RAML specifications state that `mediaType` is optional for `body` nodes.
// SE-9165
* If you tried to import a Swagger 2.0 JSON file that contained an array of objects, Design Center threw a parsing error.
// SE-9269
* The mocking service was not presenting a choice of authentication methods when a basic `securityScheme` was being referenced from a library RAML fragment.
// SE-9276
* It was possible for projects imported into Anypoint Studio from the API editor in Design Studio to contain RAML errors that were not pointed out by the API editor.
// SE-9545
* RAML errors not reported by the API editor could cause problems in the API console pane, such as failures to display various pieces of information.
// SE-9284
* If a `uses` node specified an invalid path to a library, the API editor displayed this unhelpful message:
+
----
Cannot read property 'ast' of null at (1, 0)
----
+
The message has been improved.
// SE-9994
* The API editor was allowing a blank line as the first line in RAML files.
// SE-10064
* For very large API specifications, validation and the appearance of the API Console in the API editor could require much more time than usual.
// SE-10137
* If an endpoint were simply `/`, the API editor would throw a parsing error.
// SE-10144
* In the API console of the API editor, query parameters did not appear after you clicked the *Try It* button.
// SE-10150
* In the API editor, changing the version number of an API specification that you were publishing to Exchange would change the value of all instances of the "version" keyword in the specification. Only the value for the root instance should have been changed.
// SE-10246
* When a custom datatype was declared as Int64, the range declared for the datatype was not validated. For example, the mistake in this definition -- declaring a maximum value that is too high for Int64 values -- was not caught:
+
----
my_int64:
  type: integer
  format: int64
  minimum: 1000000000000000000
  maximum: 9999999999999999999
----
// SE-10257
* Using double angle brackets (double chevrons) enclose a parameter name in resource type and trait definitions was not supported in the API editor.
// SE-10277
* Some valid regular expressions in the RAML "pattern" element were unsupported in the API editor.
// SE-10309
* In some cases, publishing an API specification to Exchange from the API editor would result in the content of the API specification being reordered incorrectly in the editor.


== 2.2.9
*August 9, 2018*

This release contains an enhancement.

=== Enhancement

If your organization contains more than one group ID, you can now select the group ID to associate an API specification with when you publish that specification to Anypoint Exchange.

== 2.2.8

*July 26, 2018*

This release introduces a change and fixes for several issues.

=== Enhancement

The code editor now supports the following structure for the declaration of a `baseUri` in specifications that are written in RAML 1.0:

[source,raml,linenums]
----
baseUri:
  value: http://www.example.com/api
----

=== Fixed Issues

* OAS files with identical names were allowed to be imported. There was no check to find out whether existing OAS 2.0 files in a project already had the same name as an OAS 2.0 file being imported.
* The `protocols` node was not being validated either in the code editor or in the visual editor.
* Error messages were not appearing for invalid `examples` nodes. Here is an example of an invalid `examples` node:

[source,raml,linenums]
----
title: New API

types:
  ids:
    type: object
    properties:
      identification:
        type: string
        examples:
          - MuleSoft
          - Salesforce
----

The correct way to define this `examples` node would be as follows:

[source,raml,linenums]
----
title: New API

types:
  ids:
    type: object
    properties:
      identification:
        type: string
        examples:
          id1: MuleSoft
          id2: Salesforce
----

The symbol `-`, which is used incorrectly in the invalid `examples` node is used for defining elements in arrays, as in this example:

[source,raml,linenums]
----
title: New API

types:
  ids:
    type: object
    properties:
      identification:
        type: array
        examples:
          id1:
            - MuleSoft
            - Salesforce
          id2:
            - Mule
            - CRM
----

* Uploading an API-specification project by using `anypoint-cli` resulted in the following message if the project contained a large number of files:
+
`Error: Could not open JPA EntityManager for transaction; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.JDBCConnectionException: Could not open connection`
* Importing an OAS 2.0 file that used parentheses in its name resulted in an error, but the error message did not explain the problem well.
* The conversion of an OAS 2.0 file to RAML, which takes place when an OAS file is imported, resulted in the `required` field in the properties of response objects being set to `false` even when the value in the OAS file was `true`.
* Attempts to import either RAML files or OAS 2.0 files via URL failed. If you tried to import a RAML file via URL, the file appeared empty in the code editor. If you tried to import an OAS 2.0 file via URL, the *Import* dialog would display the error message `Invalid OAS document`.
* When switched on, the mocking service could incorrectly insert the URI to the mocking server.
* It was possible to import an example into an API-specification project that was in read-only mode.
* If in the code editor you clicked the plus sign in the left sidebar, selected *Other* in the *Add New File* dialog, and then clicked *Create* without specifying a name for the file, a new file with the name `*/` appeared in the file list. It was not possible to delete that file.


== 2.2.7

*May 16, 2018*

This release fixes these issues:

* Supplying a base URI parameter in the visual editor, using the parameter in a base URI, closing the visual editor, and then reopening the project resulted in an error message and a blank middle panel.
* Selecting the type Number for a new Data Type in the visual editor, specifying a format, and changing the type to Integer resulted in the RAML viewer still including the specified number format.
* In the visual editor, changing the type for a base URI parameter caused the RAML viewer to show the new type, but the *Type* field continued to show the previously selected type.


== 2.2.6

*April 20, 2018*

This release fixes these issues:

* Attempts to import OAS JSON files would result in this error message being displayed: `Cannot read property 'hasOwnProperty' of null`  Such files could also fail to be converted by the JSON-to-RAML online conversion tool.
* Some warning and error messages were not being displayed.


== 2.2.5

*April 6, 2018*

This release includes two enhancements and fixes an issue.

=== Enhancements

* The left sidebar of the editor now lists groups, their resources, and their datatypes.
* An example API to use in the visual editor is now available from a link in the left sidebar.

=== Fixed Issue

The word "type" could not be used as the name of a property in a RAML API specification.
