= Anypoint Runtime Fabric Runtimes Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: runtimes, release notes, runtime fabric, runtimefabric, fabric, rtf

These are the release notes for patches which are made to the Mule runtimes on Runtime Fabric. In addition to these release notes, see the xref:runtime-fabric/runtime-fabric-release-notes.adoc[Anypoint Runtime Fabric release notes] and the complete xref:1.0@runtime-fabric::index.adoc[Anypoint Runtime Fabric] documentation.

== Feburary xx, 2019

This release adds support for the following Mule runtimes:

* Mule 3.9.2


=== 4.1.2 Runtime Update:

This release includes the following fixes:

* Added: Support for viewing and alerting on heap memory metrics.

=== 4.1.1 Runtime Update:

This release includes the following fixes:

* Added: Support for viewing and alerting on heap memory metrics.

=== 4.1.0 Runtime Update:

This release includes the following fixes:

* Added: Support for viewing and alerting on heap memory metrics.

=== 3.9.1 Runtime Update:

This release includes the following fixes:

* Added: Support for viewing and alerting on heap memory metrics.
