= Anypoint Runtime Fabric Runtimes Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: runtimes, release notes, runtime fabric, runtimefabric, fabric, rtf

These are the release notes for patches which are made to the Mule runtimes on Runtime Fabric. In addition to these release notes, see the xref:runtime-fabric/runtime-fabric-release-notes.adoc[Anypoint Runtime Fabric release notes] and the complete xref:1.0@runtime-fabric::index.adoc[Anypoint Runtime Fabric] documentation.

== May 17, 2019

This release adds the following runtimes:

 * 4.1.5 `v1.2.1`
 * 4.2.0 `v1.2.2`

== April 30, 2019

=== 4.1.4 `v1.2.1`

This release includes the following enhancements:

* Added: Anypoint Monitoring agent

=== 4.1.3 `v1.2.1`

This release includes the following enhancements:

* Added: Anypoint Monitoring agent

=== 4.1.2 `v1.2.1`

This release includes the following enhancements:

* Added: Anypoint Monitoring agent

=== 3.9.2 `v1.2.1`

This release includes the following enhancements:

* Added: Anypoint Monitoring agent

=== 3.9.1 `v1.2.1`

This release includes the following enhancements:

* Added: Anypoint Monitoring agent

=== 3.8.7 `v1.2.1`

This release includes the following enhancements:

* Added: Anypoint Monitoring agent

== March 27, 2019

=== 4.1.4 `v1.1.14`

This release includes the following fixes:

* Added: Ability to consume secure properties
* Added: Automatic API Gateway HTTP proxy configuration

=== 4.1.3 `v1.1.13`

This release includes the following fixes:

* Added: Ability to consume secure properties
* Added: Automatic API Gateway HTTP proxy configuration
* Fixed: Ability to send "Base64 Encoded client_id and client_secret" in Authorization header for authorization-code-grant-type [SE-9065]
* Fixed: Unknown error on Object Store operation [SE-9285]
* Fixed: Client Enforcement Policy throwing "No value present" error [SE-8736]
* Fixed: SDK scopes process internal chains as blocking [SE-9315]
* Fixed: Failure to process subflow with async scopes [SE-9395]
* Fixed: Batch crashes with ArrayList of HashMap as input [SE-9437]
* Fixed: Cannot open a new cursor on a closed stream using batch processing [SE-9472]
* Fixed: Invalid Session ID on SFDC connector reconnnection attempt. [SE-9471]
* Fixed: Invalid XML generated for artifact declaration [MULE-15835]

=== 4.1.2 `v1.1.5`

This release includes the following fixes:

* Added: Ability to consume secure properties
* Added: Automatic API Gateway HTTP proxy configuration
* Fixed: Unable to invoke a service using a WSDL with nested imports [SE-8362]
* Fixed: Web Service Consumer ignores CDATA tag in Consume operation [SE-8643]
* Fixed: Fixes DataWeave flatfile transformation returns empty payload [SE-8608]
* Fixed: Fixes DefaultEventContext not cleaned up [SE-8526]
* Fixed: Client Enforcement Policy throwing "No value present" error [SE-8736]

=== 3.9.2 `v1.1.9`

This release includes the following fixes:

* Added: Ability to consume secure properties
* Added: Automatic API Gateway HTTP proxy configuration
* Fixed: Partitioned object store does not delete partition folder [SE-10999]
* Fixed: Hung thread in WMQ transport with synchronous processing strategy [SE-10743]
* Fixed: XSD schemas being loaded multiple times cause delayed startup [SE-10529]
* Fixed: `ObjectDoesNotExistException` on OAuth module [SE-10423]
* Fixed: WMQ transport with synchronous processing strategy is not reconnecting [SE-10362]
* Fixed: Throttling policy doesn’t clean its cache [SE-10534]
* Fixed: Oracle type with CLOB field raises error [SE-10726]
* Fixed: Database connector file descriptor leaks when processing large payloads [SE-11071]
* Fixed: SFTP connector is not closing connections [SE-10977]

=== 3.9.1 `v1.1.15`

This release includes the following fixes:

* Added: Ability to consume secure properties
* Added: Automatic API Gateway HTTP proxy configuration
* Fixed: Hung thread in WMQ transport with synchronous processing strategy [SE-10743]
* Fixed: API console RAML validation errors [SE-8773]
* Fixed: RAML parser uncaught exception [SE-9228]
* Fixed: OAuth2 provider not working when offline; support RestClient reconnection [SE-9455]
* Fixed: Response encoding being replaced in Web Service Consumer [SE-9298]
* Fixed: Payload expression transform error [SE-9452]
* Fixed: Addressed deployment issue when using the IMAP reconnection strategy. [SE-9544]
* Fixed: LIST command is not issued after reconnection in FTP transport [SE-9323]
* Fixed: APIKit validation error doesn’t display the field name [SE-8727]
* Fixed: XSD schemas being loaded multiple times cause delayed startup [SE-10529]
* Fixed: WMQ transport with synchronous processing strategy is not reconnecting [SE-10362]
* Fixed: Oracle type with CLOB field raises error [SE-10726]
* Fixed: Database connector file descriptor leaks when processing large payloads [SE-11071]

=== 3.8.7 `v1.1.7`

This release includes the following fixes:

* Added: Ability to consume secure properties
* Added: Automatic API Gateway HTTP proxy configuration
* Fixed: Partitioned object store does not delete partition folder [SE-10999]
* Fixed: Memory leak in XsltTransformer [SE-8522]


== March 15, 2019

=== 4.1.4 `v1.1.8`

This release includes the following fixes:

 * Fixed: Event instances were kept too long in the buffer [SE-9556]
 * Fixed: DataWeave stream is closed before being consumed in batch aggregator [SE-9836]
 * Fixed: Batch process not doing "on complete" step when results collection is empty [SE-9899]
 * Fixed: Invalid Session ID on SFDC connector reconnnection attempt. [SE-9471]
 * Fixed: 'Could not deserialize object' in cache component. [SE-9879]
 * Fixed: DataWeave stream closed intermittently in a batch process. [SE-9974]
 * Fixed: Amazon SQS connector shutdown exception. [SE-9149]
 * Fixed: Backpressure is not triggered by a saturated CPU_INTENSIVE thread pool. [SE-10078]
 * Fixed: Invalid XML generated for artifact declaration [MULE-15835]
 * Fixed: ProcessingStrategy internal bufferSize is always 256 for flow-ref [SE-10226]
 * Fixed: IdempotentRedeliveryPolicy blocks CPU_LITE thread [SE-10306]
 * Fixed: Source error callback is not called when an error is caught in error handler [SE-10212]
 * Fixed: Gatekeeper policy causes memory leak on policy engine [SE-10641]
 * Fixed: Salesforce Marketing connector throws token expired exception [SE-10343]
 * Fixed: Context does not contain key error shown in the logs [SE-10867]
 * Fixed: Feedback Loop not working impacts on DoS policy behavior [AGW-2956]

== Feburary 11, 2019

=== 4.1.4

This release includes the following fixes:

* Added: Support for viewing and alerting on heap memory metrics.
* Added: Java 8u191

=== 4.1.3

This release includes the following fixes:

* Added: Support for viewing and alerting on heap memory metrics.
* Added: Java 8u191

=== 4.1.2

This release includes the following fixes:

* Added: Support for viewing and alerting on heap memory metrics.
* Added: Java 8u191

=== 4.1.1

This release includes the following fixes:

* Added: Support for viewing and alerting on heap memory metrics.
* Added: Java 8u191

=== 3.9.1

This release includes the following fixes:

* Added: Support for viewing and alerting on heap memory metrics.
* Added: Java 8u191

=== 3.8.7

This release includes the following fixes:

* Added: Support for viewing and alerting on heap memory metrics.
* Added: Java 8u191
