= Anypoint Runtime Fabric Runtimes Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: runtimes, release notes, runtime fabric, runtimefabric, fabric, rtf

These are the release notes for patches which are made to the Mule runtimes on Runtime Fabric. In addition to these release notes, see the xref:runtime-fabric/runtime-fabric-release-notes.adoc[Anypoint Runtime Fabric release notes] and the complete xref:1.0@runtime-fabric::index.adoc[Anypoint Runtime Fabric] documentation.

== March 15, 2019

=== 4.1.4 Runtime Update:

This release includes the following fixes:

 * Fixed: Event instances were kept too long in the buffer [SE-9556]
 * Fixed: DataWeave stream is closed before being consumed in batch aggregator [SE-9836]
 * Fixed: Batch process not doing "on complete" step when results collection is empty [SE-9899]
 * Fixed: Invalid Session ID on SFDC connector reconnnection attempt. [SE-9471]
 * Fixed: 'Could not deserialize object' in cache component. [SE-9879]
 * Fixed: DataWeave stream closed intermittently in a batch process. [SE-9974]
 * Fixed: Amazon SQS connector shutdown exception. [SE-9149]
 * Fixed: Backpressure is not triggered by a saturated CPU_INTENSIVE thread pool. [SE-10078]
 * Fixed: Invalid XML generated for artifact declaration [MULE-15835]
 * Fixed: ProcessingStrategy internal bufferSize is always 256 for flow-ref [SE-10226]
 * Fixed: IdempotentRedeliveryPolicy blocks CPU_LITE thread [SE-10306]
 * Fixed: Source error callback is not called when an error is caught in error handler [SE-10212]
 * Fixed: Gatekeeper policy causes memory leak on policy engine [SE-10641]
 * Fixed: Salesforce Marketing connector throws token expired exception [SE-10343]
 * Fixed: Context does not contain key error shown in the logs [SE-10867]
 
== Feburary 11, 2019

=== 4.1.4 Runtime Update:

This release includes the following fixes:

* Added: Support for viewing and alerting on heap memory metrics.
* Added: Java 8u191

=== 4.1.3 Runtime Update:

This release includes the following fixes:

* Added: Support for viewing and alerting on heap memory metrics.
* Added: Java 8u191

=== 4.1.2 Runtime Update:

This release includes the following fixes:

* Added: Support for viewing and alerting on heap memory metrics.
* Added: Java 8u191

=== 4.1.1 Runtime Update:

This release includes the following fixes:

* Added: Support for viewing and alerting on heap memory metrics.
* Added: Java 8u191

=== 3.9.1 Runtime Update:

This release includes the following fixes:

* Added: Support for viewing and alerting on heap memory metrics.
* Added: Java 8u191

=== 3.8.7 Runtime Update:

This release includes the following fixes:

* Added: Support for viewing and alerting on heap memory metrics.
* Added: Java 8u191
