= Anypoint Runtime Fabric Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: release notes, runtime fabric, runtimefabric, fabric, rtf

In addition to these release notes, see the complete xref:1.0@runtime-fabric::index.adoc[Anypoint Runtime Fabric] documentation.

== 1.1.100 - October 16, 2018

This release includes the following fixes:

* Fixed: Runtime Fabric reports disconnected status when leader is re-elected in some cases.
* Fixed: Cluster status is not reported after connection to control plane is re-established.

== 1.1.87 - October 5, 2018

This release includes the following fixes:

* Fixed: Unable to restart services if Runtime Fabric is offline for more than 12 hours.
* Fixed: Removed sensitive resource URLs from log output.
* Fixed: Side-channel test of connection to control plane when running via proxy.
* Fixed: Increased time allowed for connecting to control plane during installation.

== 1.1.55 - September 19, 2018

This release includes the following fixes and enhancements:

* Added: Monitoring dashboard in Ops Center to provide more visibility on the health of the inbound traffic controller and Mule applications.
* Added: Support for directing outbound traffic of Runtime Fabric services through an HTTP and TCP proxy.
* Added: Support for running Runtime Fabric services with an existing user and group ID.

* Fixed: Ingress resources were not removed when inbound traffic is disabled.
* Fixed: Some environments were not visible as a filter in Ops Center monitoring dashboard.
* Fixed: Inbound traffic controller health probes occasionally reported unhealthy under high CPU load.
* Fixed: The last mile security setting was not correctly applied in some cases.
* Fixed: Application updates can cause disruption of inbound traffic in certain cases.

== 1.0.1 - August 13, 2018

This release marks the general availability of Anypoint Runtime Fabric.

* Support for the following Mule runtime and API gateway versions:
** Mule 4.1.2
** Mule 3.9.1
** Mule 3.8.7
